import { CheckboxGroup, FieldError, FormActions, RadioGroup, TextAreaField } from "./FormControls";

const supportAreas = ["Making introductions", "Contacting businesses", "Building corporate partnerships", "Asking individual donors", "Hosting events", "Grant prospecting", "Reviewing proposals", "Sharing campaigns", "Recruiting volunteers", "Building community relationships", "Serving on a fundraising committee", "We have not discussed this with them", "They are not currently willing to help"];
const missingElements = ["A clear fundraising strategy", "Board fundraising responsibilities", "A fundraising committee", "A fundraising team", "Corporate funding strategy", "Major-donor strategy", "Grant strategy", "Fundraising content and materials", "Case for support", "Proposals", "Consistent follow-up", "Consistent execution", "We are not sure what is missing"];

export const StepFour = ({ data, update, errors, onBack, onSubmit, submitting, submitError }) => <div className="form-step" data-testid="assessment-step-4">
  <div className="form-title"><p className="eyebrow">Step 4 of 4</p><h1 data-testid="step-4-heading">Tell Us About Your Board’s Fundraising</h1><p data-testid="step-4-description">Show us how your board participates in fundraising now.</p></div>
  <RadioGroup name="present_fundraising_involvement" label="Are any of your present board members currently helping the organization raise money?" value={data.present_fundraising_involvement} update={update} error={errors.present_fundraising_involvement} options={["Yes, most of them", "Yes, a few of them", "Only one person", "No", "Not sure"]} />
  <CheckboxGroup name="board_support_areas" label="What are your board members currently willing and confident to help with?" value={data.board_support_areas} update={update} error={errors.board_support_areas} options={supportAreas} />
  <RadioGroup name="written_fundraising_strategy" label="Does your organization have a written fundraising strategy?" value={data.written_fundraising_strategy} update={update} error={errors.written_fundraising_strategy} options={["Yes", "No", "We have one, but the board is not involved", "We need to update it", "Not sure"]} />
  <RadioGroup name="individual_responsibilities" label="Do your board members understand their individual fundraising responsibilities?" value={data.individual_responsibilities} update={update} error={errors.individual_responsibilities} options={["Yes", "Some of them", "No", "We have never assigned individual fundraising responsibilities."]} />
  <RadioGroup name="board_participation_in_planning" label="Has the board participated in creating or adopting the fundraising strategy?" value={data.board_participation_in_planning} update={update} error={errors.board_participation_in_planning} options={["Yes", "No", "We do not currently have a fundraising strategy."]} />
  <CheckboxGroup name="missing_fundraising_elements" label="Which parts of your fundraising system are currently missing?" value={data.missing_fundraising_elements} update={update} error={errors.missing_fundraising_elements} options={missingElements} />
  <TextAreaField name="desired_result" label="What result would make this board transformation successful for you?" value={data.desired_result} update={update} error={errors.desired_result} />
  <RadioGroup name="support_required" label="What type of support do you need?" value={data.support_required} update={update} error={errors.support_required} options={["Show me what to do and provide everything I need to execute it myself.", "Work with me one-on-one while I execute.", "Take charge of the board transformation process with me.", "I am not sure. Tell me what you recommend."]} />
  <TextAreaField name="additional_information" label="Is there anything else we should know about your present board?" value={data.additional_information} update={update} error={errors.additional_information} required={false} />
  <label className={`confirmation-check ${data.confirmation_accepted ? "selected" : ""}`} data-testid="confirmation-accepted-field"><input type="checkbox" checked={data.confirmation_accepted} onChange={(event) => update("confirmation_accepted", event.target.checked)} data-testid="confirmation-accepted-checkbox" /><span>I confirm that the information provided is accurate and that Nonprofit Board Builder may contact me about transforming our board.</span></label>
  <FieldError name="confirmation_accepted" message={errors.confirmation_accepted} />
  <label className={`confirmation-check optional-consent ${data.marketing_consent ? "selected" : ""}`} data-testid="nonprofit-marketing-consent-field"><input type="checkbox" checked={data.marketing_consent} onChange={(event) => update("marketing_consent", event.target.checked)} data-testid="nonprofit-marketing-consent-checkbox" /><span>Yes, email me future board-building resources, services and offers from Nonprofit Board Builder. I understand that I can unsubscribe at any time.</span></label>
  {submitError && <p className="submit-error" data-testid="assessment-submit-error">{submitError}</p>}
  <FormActions onBack={onBack} onNext={onSubmit} final submitting={submitting} />
</div>;