import { CheckboxGroup, FormActions, RadioGroup, TextField } from "./FormControls";

const conditions = ["We do not currently have a complete board.", "Most of the work is being carried by the founder or Executive Director.", "Some board members have stopped attending meetings.", "Some board members attend but do not take responsibility.", "Our board members are committed but do not know what to do.", "Our board members are not involved in fundraising.", "We have people on the board who may need to step down.", "We have a good board but need more skills, experience and connections.", "We need to build the board almost from the beginning.", "Something else."];

export const StepTwo = ({ data, update, errors, onBack, onNext }) => <div className="form-step" data-testid="assessment-step-2">
  <div className="form-title"><p className="eyebrow">Step 2 of 4</p><h1 data-testid="step-2-heading">Tell Us About Your Present Board</h1><p data-testid="step-2-description">Give us a clear picture of your board today.</p></div>
  <div className="form-grid two-col"><TextField name="bylaws_board_size" label="How many board members are you required to have according to your bylaws?" value={data.bylaws_board_size} update={update} error={errors.bylaws_board_size} placeholder="Number or Not sure" /><TextField name="current_board_size" label="How many board members do you currently have?" type="number" value={data.current_board_size} update={update} error={errors.current_board_size} /><TextField name="active_board_members" label="How many of your present board members are consistently active?" type="number" value={data.active_board_members} update={update} error={errors.active_board_members} /><TextField name="inactive_board_members" label="How many are inactive, inconsistent or no longer attending meetings?" type="number" value={data.inactive_board_members} update={update} error={errors.inactive_board_members} /></div>
  <CheckboxGroup name="present_board_condition" label="Which description best explains your present board?" value={data.present_board_condition} update={update} error={errors.present_board_condition} options={conditions} />
  <RadioGroup name="board_type" label="What type of board are you trying to build?" value={data.board_type} update={update} error={errors.board_type} options={["Governing board", "Working board", "Fundraising board", "Advisory board", "A combination", "Not sure"]} />
  <RadioGroup name="commitment_conversations" label="Have you had individual conversations with inactive board members about recommitting?" value={data.commitment_conversations} update={update} error={errors.commitment_conversations} options={["Yes", "No", "With some of them"]} />
  <RadioGroup name="willing_to_allow_step_down" label="Are you willing to allow board members who will not recommit or contribute to step down?" value={data.willing_to_allow_step_down} update={update} error={errors.willing_to_allow_step_down} options={["Yes", "No", "I need guidance before making that decision."]} />
  <RadioGroup name="bylaw_clarity" label="Do your bylaws clearly explain board terms, resignation and removal?" value={data.bylaw_clarity} update={update} error={errors.bylaw_clarity} options={["Yes", "No", "Not sure"]} />
  <FormActions onBack={onBack} onNext={onNext} />
</div>;