import { CheckboxGroup, FormActions, RadioGroup, SelectField, TextAreaField, TextField } from "./FormControls";
import { stepThreeText } from "../../content/siteContent";

const areas = ["Fundraising", "Corporate partnerships", "Grant development", "Major donors", "Financial management", "Legal support", "Marketing", "Public relations", "Community outreach", "Program development", "Volunteer recruitment", "Strategic planning", "Governance", "Technology", "Operations", "Connections and introductions", "Lived experience connected to our mission", "Something else."];

export const StepThree = ({ data, update, errors, onBack, onNext }) => <div className="form-step" data-testid="assessment-step-3">
  <div className="form-title"><p className="eyebrow">Step 3 of 4</p><h1 data-testid="step-3-heading">{stepThreeText.tellUsWhichBoardMembers}</h1><p data-testid="step-3-description">{stepThreeText.defineTheExperienceSkillsAnd}</p></div>
  <div className="form-grid two-col"><TextField name="new_board_members_needed" label="How many new board members would you like to recruit?" type="number" value={data.new_board_members_needed} update={update} error={errors.new_board_members_needed} /><SelectField name="recruitment_timeline" label="How soon do you need them?" value={data.recruitment_timeline} update={update} error={errors.recruitment_timeline} options={["Within 30 days", "Within 60 days", "Within 90 days", "Within six months", "Not sure"]} /></div>
  <CheckboxGroup name="areas_carried_alone" label="What areas have you been carrying alone that you need board members to help with?" value={data.areas_carried_alone} update={update} error={errors.areas_carried_alone} options={areas} />
  <TextAreaField name="missing_skills_networks" label="Which skills, experience or networks are missing from your present board?" value={data.missing_skills_networks} update={update} error={errors.missing_skills_networks} />
  <TextAreaField name="expected_new_member_benefit" label="How do you expect the new board members to strengthen your organization?" value={data.expected_new_member_benefit} update={update} error={errors.expected_new_member_benefit} />
  <RadioGroup name="people_already_identified" label="Do you already know people you would like to invite to join the board?" value={data.people_already_identified} update={update} error={errors.people_already_identified} options={["Yes", "No", "We know some people but need more candidates."]} />
  <TextAreaField name="benefits_of_joining" label="What benefits can your organization offer someone who joins the board?" value={data.benefits_of_joining} update={update} error={errors.benefits_of_joining} helper="List the strongest reasons a qualified person should want to join and help build your organization." />
  <RadioGroup name="previous_recruitment_experience" label="Have you recruited board members before?" value={data.previous_recruitment_experience} update={update} error={errors.previous_recruitment_experience} options={["Yes, successfully", "Yes, but the people recruited did not become active", "We tried but did not receive enough qualified applicants", "No, this will be our first structured recruitment", "Not sure"]} />
  <FormActions onBack={onBack} onNext={onNext} />
</div>;