"""Canonical 100-topic board content library. Do not modify topic titles."""

BOARD_CONTENT_TOPICS = {
    "transformation": [
        "Why Your Board Is Holding Your Nonprofit Back",
        "Your Board Was Meant to Lead the Organization. Why Is It Watching From Behind?",
        "Why Passionate Board Members Can Still Become a Bottleneck",
        "How to Know When Your Board Has Become a Bottleneck",
        "Why Your Board Is the Way It Is",
        "The Real Reason Your Board Is Disengaged",
        "Why Your Board Members Are Not Taking Responsibility",
        "What Happens When Your Board Does Not Understand Its Role",
        "Your Board Should Be Helping You Build the Organization",
        "The Founder Should Not Be Carrying the Board\u2019s Responsibility Alone",
        "The Difference Between Having a Board and Having a Board That Works",
        "What a Powerhouse Nonprofit Board Actually Looks Like",
        "How to Build a Board That Commits to Your Mission",
        "How to Turn Your Board From a Bottleneck Into an Asset",
        "The Complete Board Transformation Process",
        "Why Board Transformation Starts With Understanding Your Current Board",
        "How to Audit Your Board Before You Recruit Anyone",
        "Why You Should Reactivate Your Board Before Replacing It",
        "When Should You Reactivate a Board Member and When Should They Step Down?",
        "How to Recruit the Right People for Your Nonprofit Board",
        "Why the Right Board Members Can Change the Direction of Your Organization",
        "How to Build a Board That Helps Raise Money",
        "How Your Board Can Help Build Your Organization\u2019s Fundraising System",
        "How to Transform Your Board Into a Team That Works With You",
        "Your Board Can Help You Fund, Grow and Scale Your Organization",
    ],
    "recruitment": [
        "Why Your Nonprofit Needs New Board Members",
        "How to Know When It Is Time to Recruit New Board Members",
        "Why Your Board Recruitment Efforts Are Not Bringing You the Right People",
        "How to Recruit Board Members Who Actually Want to Serve",
        "What Makes Someone the Right Board Member for Your Organization?",
        "Why You Should Recruit for Your Board Based on What Your Organization Needs",
        "How to Build a Board That Commits to Your Mission",
        "What a Powerhouse Board Looks Like",
        "Why Recruiting More Board Members Won\u2019t Fix a Weak Board",
        "What to Look for When Recruiting Your Next Board Member",
        "How to Recruit Board Members Who Bring More Than Their R\u00e9sum\u00e9",
        "Why Your Board Needs People With the Right Skills and Connections",
        "How to Recruit Board Members Who Can Help Your Organization Raise Money",
        "Why Your Board Recruitment Campaign Matters",
        "How to Create a Board Recruitment Campaign That Attracts Quality Professionals",
        "Where to Find Quality Professionals for Your Nonprofit Board",
        "How to Get Professionals Interested in Serving on Your Board",
        "How to Get the Right People to Apply to Join Your Board",
        "Why Your Board Recruitment Application Matters",
        "How to Launch Your Board Recruitment Campaign in 30 Minutes",
        "Why Recruiting the Right Board Members Changes Everything",
        "How to Build a Board That Can Help You Fund, Grow and Scale",
        "How to Recruit Board Members Who Share Your Mission",
        "What to Do After Your Board Recruitment Campaign Launches",
        "How to Start Building the Board Your Nonprofit Needs",
    ],
    "reactivation": [
        "Why Your Board Isn\u2019t Showing Up for Your Nonprofit",
        "Why Your Board Members Have Become Disengaged",
        "How to Know If Your Board Needs Reactivation",
        "Your Board Members Agreed to Serve. Why Aren\u2019t They Serving?",
        "Why Board Members Stop Participating",
        "Why Your Board Meetings Are Not Producing Results",
        "Why Your Board Members Are Watching From Behind",
        "Why Sending More Emails Won\u2019t Reactivate Your Board",
        "Why Reminding Your Board About Their Responsibilities Isn\u2019t Enough",
        "How to Get Your Board Members to Start Taking Responsibility",
        "How to Reconnect Your Board Members With the Mission",
        "How to Find Out Why Your Board Members Became Disengaged",
        "Why You Need to Understand Your Board Before You Try to Change It",
        "How to Audit Your Board Before Reactivating It",
        "How to Get Your Board Members to Recommit",
        "When a Board Member Should Recommit and When They Should Step Down",
        "How to Reactivate a Disengaged Board",
        "How to Get Your Board Members to Start Showing Up Again",
        "How to Get Your Board Members to Start Taking Action",
        "How to Turn a Passive Board Into an Active Board",
        "How to Build Accountability Into Your Board",
        "How to Get Your Board Working With You Again",
        "Why Board Reactivation Can Change the Direction of Your Organization",
        "The Board Reactivation Process",
        "How to Reactivate Your Board and Get Them Working With You Again",
    ],
    "fundraising_activation": [
        "Why Your Board Isn\u2019t Raising Money for Your Nonprofit",
        "Your Board\u2019s Responsibility: Ensuring Your Organization Is Adequately Funded",
        "Why Telling Your Board to \u201cRaise Money\u201d Doesn\u2019t Work",
        "Your Board Members Aren\u2019t Professional Fundraisers. Here\u2019s How You Get Them to Raise Money",
        "Why Fundraising Targets Can Actually Disengage Your Board",
        "How to Get Your Board to Start Raising Money Without Forcing Them",
        "The Board Fundraising Activation Process",
        "Stop Asking Your Board to Raise Money. Start Asking How They Want to Support Fundraising",
        "How to Turn Each Board Member\u2019s Strength Into a Fundraising Opportunity",
        "Why Your Board Should Help Build Your Fundraising System",
        "Your Board Is Not Your Fundraising Team",
        "How a Board Can Raise Money Without Personally Asking Everyone for Money",
        "How Board Members Can Use Their Networks to Raise Money",
        "The Difference Between a Fundraising Board and a Board That Is Told to Fundraise",
        "Why Those Who Plan Together Execute Together",
        "How to Get Your Board to Help Create Your Fundraising Strategy",
        "How to Build a Board-Backed Fundraising Strategy Plan",
        "Why Your Board Should Approve and Adopt Your Fundraising Strategy",
        "How to Give Every Board Member a Fundraising Portfolio",
        "How to Activate Board Members Based on Their Area of Strength",
        "How Your Board Can Help Build the Fundraising Team",
        "Why Your Nonprofit Needs a Fundraising System Your Board Can Support",
        "How to Get Your Board to Make Introductions for Your Nonprofit",
        "How to Build a Fundraising Board That Can Help You Raise Your First $100K",
        "How to Activate Your Board to Raise Money for Your Organization",
    ],
}
