"""Board Fundraising Game V3: simplified 4-round / 8-question game. All customer copy lives here (admin-editable defaults)."""

PARTICIPATION_BUILD_OPTIONS = [
    "Identify potential funders", "Research potential funders", "Recruit people to help with fundraising",
    "Manage or coordinate the fundraising team", "Build or manage the CRM / donor database",
    "Set up or manage fundraising technology", "Create or improve fundraising materials", "Create fundraising content",
    "Manage follow-up and relationship tracking", "Help organize fundraising events",
    "Track fundraising activity and results", "Help improve the fundraising strategy and process", "Other",
]

PARTICIPATION_RAISE_OPTIONS = [
    "Introduce the organization to people I know", "Introduce the organization to businesses I know",
    "Introduce the organization to grantmakers or funders I know", "Identify potential individual donors",
    "Identify potential business partners or sponsors", "Identify potential grant opportunities",
    "Attend donor or funder meetings", "Make fundraising asks", "Follow up with potential funders",
    "Build relationships with potential funders", "Steward and thank existing funders",
    "Invite people to fundraising events", "Share fundraising campaigns and content with my network",
    "Host a small gathering or introduction meeting", "Other",
]

TIME_OPTIONS = ["1–2 hours", "3–5 hours", "6–10 hours", "10+ hours", "It depends on what I am helping with"]

GAME_V3 = {
    "intro": {
        "heading": "Build Your Fundraising Strategy By Playing The Game",
        "paragraphs": [
            "To raise money exponentially, you need to build your organization's fundraising system.",
            "To build your organization's fundraising system, you need to know the exact type of people, businesses and grantors meant to fund your mission, where to find them, how to attract them and the exact process to raise money from them.",
        ],
        "strategy_heading": "That's What We Call The Fundraising Strategy",
        "completion_text": "By completing this game, you will create a clear fundraising strategy to reach your organization's fundraising goal.",
        "goal_label": "Your Fundraising Goal",
        "cta": "Get Started",
    },
    "rounds": [
        {
            "key": "who_should_fund",
            "label": "ROUND 1 OF 4",
            "heading": "Who Has The Greatest Reason To Fund Your Mission?",
            "teaching": "Not every individual, business or grantor is meant to give to your mission.\n\nThere are people, businesses and grantors with strong reasons to give and see your mission succeed.\n\nUse the questions below to guide your thinking.",
            "first_label": "Your First Thoughts",
            "first_question": "Before going through the questions below, who do you think are the exact types of people, businesses and grantors meant to fund your mission or with the greatest reason to fund your organization?",
            "guides": [
                {"heading": "Think About Individuals", "items": [
                    "Who has personally experienced the problem your organization is solving?",
                    "Who has a family member, friend or someone they care about affected by the problem you are solving?",
                    "Who strongly believes in the cause, issue or change your organization exists to create?",
                    "Who benefits from seeing the people or community you serve become stronger, healthier or more successful?",
                    "Who already spends time, attention or money supporting issues connected to your mission?",
                    "Who has a personal, professional, community or emotional connection to the people you serve?",
                    "Who has both a reason to care and the ability to financially support your mission?",
                ], "note": "Do not simply write \"individual donors.\" Describe the exact type of people who have the greatest reason to want your mission to succeed."},
                {"heading": "Think About Businesses", "items": [
                    "Which businesses serve the same people your organization serves?",
                    "Which businesses employ people from the communities or groups you serve?",
                    "Which businesses sell products or services connected to the problem your organization solves?",
                    "Which businesses benefit when the people, community or issue you serve improves?",
                    "Which businesses have community, social impact or corporate responsibility priorities connected to your mission?",
                    "Which businesses are already supporting organizations, causes or communities similar to yours?",
                ], "note": "Do not simply write \"local businesses\" or \"corporate sponsors.\" Identify the exact type of businesses with a real reason to see your mission succeed."},
                {"heading": "Think About Grantors", "items": [
                    "Which grantors already fund the issue your organization is solving?",
                    "Which grantors fund the exact people or communities your organization serves?",
                    "Which grantors fund organizations working in your location?",
                    "Which grantors fund the type of program, intervention or outcome your organization creates?",
                ], "note": "The strongest grant opportunities usually come from funders whose existing funding focus already connects directly with your mission."},
            ],
            "final_label": "Now Sharpen Your Answer",
            "final_question": "Based on what you just learned, who are the exact types of people, businesses and grantors meant to fund your mission or with the greatest reason to fund your organization?",
            "cta": "Continue To Round 2",
        },
        {
            "key": "where_to_find",
            "label": "ROUND 2 OF 4",
            "heading": "Where Can You Find Them?",
            "teaching": "Now that you know who you are looking for, to find them, all you have to do is go where they congregate.\n\nFor example, if you are looking for Christians, you go to the church. If you are looking for Muslims, you go to the mosque.\n\nThe same principle applies to the exact people, businesses and grantors you want to reach.",
            "first_label": "Your First Thoughts",
            "first_question": "Looking at the people, businesses and grantors you identified, where do you think you can find them?",
            "person_prompt": "Where do they already spend their time, build relationships, learn, work, meet other people or participate in communities?",
            "business_prompt": "What industries, business networks, associations, chambers, LinkedIn communities, directories, events or local business communities are they part of?",
            "grantor_prompt": "Where can you identify them, learn what they fund, see organizations they already support, attend their events or connect with the people responsible for their funding priorities?",
            "teaching_note": "You do not need to search everywhere. Go to the places where the exact funders you want already congregate.",
            "final_label": "Now Sharpen Your Answer",
            "final_question": "Where Can You Consistently Find The Funders You Identified?",
            "final_input_label": "Where can you consistently find them?",
            "cta": "Continue To Round 3",
        },
        {
            "key": "attract_attention",
            "label": "ROUND 3 OF 4",
            "heading": "How Can You Attract Them To Your Organization?",
            "teaching": "You don't have to run around chasing prospects.\n\nYou can provide something valuable that will attract them to your organization first.\n\nThe goal is to give the exact people, businesses and grantors you want to reach a reason to notice your organization, connect with you and give you a way to continue the conversation.",
            "first_label": "Your First Thoughts",
            "first_question": "What can your organization offer the people, businesses and grantors you identified that would make them want to connect with you?",
            "example_text": "If one of the audiences you want to attract is [AUDIENCE NAME], what can your organization create, offer or invite them into that would be valuable enough for them to stop, pay attention and connect with you?",
            "examples": [
                "A useful guide", "A checklist", "A report", "A survey", "An assessment", "A form", "A webinar",
                "An educational session", "An event", "A community activity", "A call for change",
                "A campaign they can participate in", "A petition", "A useful resource",
                "An opportunity to share their opinion", "An invitation to contribute to something meaningful",
                "Another valuable reason to connect",
            ],
            "teaching_note": "The first goal is not always to ask them for money.\n\nThe first goal is to attract their attention, get them to connect with your organization and create the opportunity to build the relationship.",
            "final_label": "Now Sharpen Your Answer",
            "final_question": "What Can You Offer Each Audience To Attract Their Attention?",
            "final_input_label": "What valuable thing can you offer them to attract their attention and get them to connect with your organization?",
            "cta": "Continue To Round 4",
        },
        {
            "key": "fundraising_process",
            "label": "ROUND 4 OF 4",
            "heading": "How Will You Raise Money From Them?",
            "teaching": "You don't raise money by reaching out to people when they connect with you for the first time and immediately asking them for money.\n\nThat is what a beggar does, and that is why people hardly give to them. When people do give, they usually give money they can do away with.\n\nTo raise money, you must patiently follow a clear process that gets people to know you, like you and trust you before getting them to give.",
            "first_label": "Your First Thoughts",
            "first_question": "Once the people, businesses and grantors you identified connect with your organization, how do you think you should raise money from them?",
            "process_heading": "The Fundraising Process",
            "process_line": "KNOW → LIKE → TRUST → ASK → FOLLOW UP → STEWARD",
            "process_steps": [
                {"key": "KNOW", "text": "They first need to know your organization exists and understand the problem you are solving."},
                {"key": "LIKE", "text": "Give them reasons to stay connected, pay attention and become interested in your mission and the work you are doing."},
                {"key": "TRUST", "text": "Help them see your impact, understand your leadership, believe in your ability to deliver and become confident that supporting your organization is worthwhile."},
                {"key": "ASK", "text": "Once the relationship and interest are strong enough, make a clear and appropriate request for financial support."},
                {"key": "FOLLOW UP", "text": "Not everyone will make a decision immediately. Continue the conversation, answer questions, stay connected and follow up."},
                {"key": "STEWARD", "text": "When they support your organization, thank them, show them what their support made possible, continue the relationship and give them a reason to support you again."},
            ],
            "example_text": "Imagine [AUDIENCE NAME] sees something valuable your organization created and connects with you.\n\nThey now KNOW you.\n\nYou continue giving them useful information, stories, opportunities or conversations that connect them more deeply to the mission. They begin to LIKE what you are doing.\n\nYou show them your impact, your work and why your organization can be trusted to create the change you promised. They begin to TRUST you.\n\nWhen the relationship is ready, you ASK them to support the mission.\n\nIf they are not ready immediately, you FOLLOW UP.\n\nWhen they give, you STEWARD the relationship by thanking them, showing their impact and keeping them connected.",
            "teaching_note": "This is how fundraising becomes a system instead of constantly chasing people and asking strangers for money.",
            "final_label": "Now Build Your Process",
            "final_question": "Based on what you just learned, what ideas come to mind for how your organization can move the people, businesses and grantors you identified through KNOW → LIKE → TRUST → ASK → FOLLOW UP → STEWARD?",
            "cta": "Complete My Fundraising Game",
        },
    ],
    "strategy_ready": {
        "heading": "Your Fundraising Strategy Is Ready",
        "completed_intro": "You just identified:",
        "completed_areas": [
            "The exact type of people, businesses and grantors meant to fund your mission or with the greatest reason to fund your organization",
            "Where to consistently find potential funders",
            "How to attract their attention",
            "The exact process to raise money exponentially for your organization",
        ],
        "imagine_heading": "Now Imagine Your Entire Board Doing This With You.",
        "more_people_statement": "The more the people that play the game, the more ideas you have on how to raise money and the more support you have when raising money and building the system that drives the strategy.",
        "locked_sections": [
            "The Exact Type Of People, Businesses and Grantors Meant To Fund Your Mission",
            "Where To Consistently Find Them",
            "How To Attract Their Attention",
            "The Exact Process To Raise Money Exponentially For Your Organization",
        ],
        "upgrade_heading": "Bring Your Board Into The Game",
        "upgrade_supporting": "Unlock the fundraising strategy you just created, invite your board members to play the game, bring everyone's ideas together during your next board meeting and build the final fundraising strategy your board will execute together.",
        "upgrade_cta": "Unlock My Fundraising Strategy + Board Fundraising Game — $497",
    },
    "current_reality": {
        "heading": "Tell Us What You Already Have",
        "supporting": "You have decided who you want to raise money from, where to find them, how to attract them and the process to raise money from them.\n\nNow tell us what your organization already has so we can build the fundraising system needed to execute your strategy around your present reality.",
        "questions": [
            {"key": "current_individual_donors", "heading": "Your Present Individual Donors", "question": "Tell us about the individual donors currently giving to your organization. Who are they, how do they usually give and what do you know about why they support your mission?"},
            {"key": "current_businesses", "heading": "Businesses Supporting You", "question": "Tell us about the businesses currently giving to or supporting your organization. Who are they and what kind of support do they provide?"},
            {"key": "current_grantors", "heading": "Grantors Funding You", "question": "Tell us about the grantors currently funding your organization. Who are they, what do they fund and how did you first connect with them?"},
            {"key": "current_team", "heading": "Your Present Fundraising Team", "question": "Who currently helps your organization raise money and what does each person currently do?"},
            {"key": "current_resources", "heading": "The Resources You Already Use", "question": "What tools, technology, fundraising materials and other resources are you currently using to raise money and manage relationships with funders?"},
        ],
    },
    "participation": {
        "heading": "How Do You Want To Be Involved?",
        "build_question": "How do you want to be involved in building and managing your organization's fundraising system?",
        "build_options": PARTICIPATION_BUILD_OPTIONS,
        "build_other_prompt": "Tell us how else you want to help build or manage the fundraising system.",
        "raise_question": "How do you want to be involved in raising money for your organization?",
        "raise_options": PARTICIPATION_RAISE_OPTIONS,
        "raise_other_prompt": "Tell us how else you want to help raise money.",
        "time_question": "How much time can you realistically commit each month?",
        "time_options": TIME_OPTIONS,
    },
    "board_completion": {
        "heading": "You're Ready For Game Night",
        "supporting": "Your ideas are now part of your organization's Board Fundraising Game.",
        "more_people_statement": "The more the people that play the game, the more ideas you have on how to raise money and the more support you have when raising money and building the system that drives the strategy.",
        "game_night_text": "During Game Night, your board will review everyone's ideas, prioritize the strongest opportunities and use those decisions to build the fundraising strategy your organization will execute together.",
    },
    "fine_tuning": {
        "heading": "Here's How We Understood Your Ideas",
        "supporting": "We fine-tuned each of your ideas so they are specific enough to search for, find and act on. Nothing is final without your approval. For each idea, choose the version that best represents what you meant.",
        "working": "Fine-tuning your ideas…",
        "your_idea_label": "Your Idea",
        "refined_label": "Fine-Tuned Version",
        "use_button": "Use This",
        "keep_button": "Keep My Original Idea",
        "edit_button": "Edit My Idea",
        "save_button": "Save My Approved Ideas",
        "empty_note": "You did not add any ideas for this area, so there is nothing to fine-tune here.",
        "area_titles": [
            "The Exact Type Of People, Businesses and Grantors Meant To Fund This Mission",
            "Where To Consistently Find Them",
            "How To Attract Their Attention",
            "The Exact Process To Raise Money Exponentially For The Organization",
        ],
    },
    "mini_strategy": {
        "heading": "Your Personal Fundraising Strategy",
        "supporting": "This is the fundraising thinking you just created for {organization}. Your approved ideas will be reviewed with the rest of the board during Game Night.",
        "people_heading": "The Exact Type Of People, Businesses and Grantors Meant To Fund This Mission",
        "individuals_label": "People",
        "businesses_label": "Businesses",
        "grantors_label": "Grantors",
        "find_heading": "Where To Consistently Find Them",
        "attract_heading": "How To Attract Their Attention",
        "process_heading": "The Exact Process To Raise Money Exponentially For The Organization",
        "build_heading": "How I Want To Help Build And Manage The Fundraising System",
        "raise_heading": "How I Want To Help Raise Money",
        "time_heading": "My Time Commitment",
        "continue_button": "Continue",
    },
    "primary_review": {
        "heading": "Review The Fundraising Strategy You Created",
        "supporting": "Before we build your complete working fundraising strategy, review how we understood the ideas you contributed while playing your game. We fine-tuned each idea so it is specific enough to search for, find and act on. You approve every idea.",
        "start_button": "Start My Strategy Review",
        "play_first_heading": "Play Your Board Fundraising Game First",
        "play_first_text": "Your fundraising strategy is created from the answers you give while playing the game. Play your game first, then come back to complete your setup.",
        "play_first_button": "Play My Board Fundraising Game",
        "generate_heading": "Generate Your Complete Working Fundraising Strategy",
        "generate_text": "We will combine your approved ideal funders, where to consistently find them, how to attract their attention, your exact process to raise money, your fundraising goal and deadline, your current donors, business supporters, grantors, team and resources, and how you want to participate — then build the complete working fundraising strategy your organization can start executing, including the people, technology, materials, resources and timeline needed to execute it.",
        "generate_button": "Generate My Complete Working Fundraising Strategy",
        "generating_text": "Building your complete working fundraising strategy… This can take a minute. Please keep this page open.",
        "generated_heading": "Your Complete Working Fundraising Strategy Is Ready",
        "generated_text": "Review your complete strategy. When you are ready, set your Game Night and invite your board members to play — their ideas will make the strategy even stronger.",
        "generated_button": "View My Complete Working Fundraising Strategy",
        "failed_heading": "We Couldn't Generate Your Strategy",
        "failed_text": "Something went wrong while building your strategy. Please try again.",
        "try_again_button": "Try Again",
    },
    "group_complete": {
        "heading": "Your Board Has Completed The Fundraising Game",
        "supporting": "Your board reviewed everyone's ideas across the four strategic areas and prioritized the strongest opportunities. The next step is turning those decisions into your organization's complete fundraising strategy — including the team, technology, materials, resources and timeline needed to execute it.",
        "cta": "Generate Our Complete Fundraising Strategy",
    },
    "guided": {
        "sections": [
            {
                "id": 1,
                "heading": "WHO SHOULD FUND YOUR MISSION?",
                "why": [
                    "The first thing you need to know is exactly who has the greatest reason to fund your mission.",
                    "If you don't know who you are looking for, fundraising becomes random.",
                    "You end up asking everybody instead of intentionally building relationships with the people, businesses and grantors most likely to care about what your organization exists to do.",
                ],
                "q1": "Who do you think are the exact types of people, businesses and grantors meant to fund your mission or with the greatest reason to fund your organization?",
                "q1_hint": "Don't overthink it. Just share the ideas that come to mind.",
                "deeper_heading": "LET'S THINK A LITTLE DEEPER",
                "deeper": [
                    "You are not simply looking for people who have money.",
                    "You are looking for people, businesses and grantors with a strong reason to care about your mission.",
                    "For people, think about who has personally experienced the problem, has a family connection to it, works around it, strongly believes in the cause or already supports something connected to it.",
                    "For businesses, think about who serves the same people, employs the people you serve, sells something connected to the issue, benefits when the community improves or already supports similar causes.",
                    "For grantors, think about who already funds your issue, your population, your geography, your type of program or the outcome you are trying to create.",
                    "Don't simply say parents, businesses or foundations.",
                    "Be specific enough that you could actually go out and find them.",
                ],
                "q2": "Based on what you just learned, who are the exact types of people, businesses and grantors with the greatest reason to fund your organization?",
            },
            {
                "id": 2,
                "heading": "WHERE CAN YOU CONSISTENTLY FIND THEM?",
                "why": [
                    "Knowing who should fund your mission is only useful if you know where to consistently find them.",
                    "To build a fundraising system, you need repeatable places where the exact people, businesses and grantors you want already gather, work, network, learn or can be identified.",
                    "If you are looking for Christians, you go to the church.",
                    "If you are looking for Muslims, you go to the mosque.",
                    "The same principle applies to your funders.",
                ],
                "q1": "Looking at the people, businesses and grantors you identified, where do you think you can consistently find them?",
                "q1_hint": "Share your first ideas.",
                "deeper_heading": "GO WHERE THEY ALREADY CONGREGATE",
                "deeper": [
                    "Now look at each audience you identified.",
                    "For people, think about where they spend time, work, learn, build relationships, join communities or attend events.",
                    "For businesses, think about industry associations, chambers, business networks, LinkedIn, conferences, directories and professional communities.",
                    "For grantors, think about funding databases, existing grantee lists, community foundations, funder networks, information sessions, conferences and the people responsible for their funding programs.",
                    "You don't need to search everywhere.",
                    "Go where the exact funders you want already congregate.",
                ],
                "q2": "Where can you consistently find each of the funders you identified?",
            },
            {
                "id": 3,
                "heading": "HOW CAN YOU ATTRACT THEIR ATTENTION?",
                "why": [
                    "Finding potential funders is not enough.",
                    "If every interaction begins with asking people for money, you will spend your time chasing people.",
                    "A fundraising system gives the exact people, businesses and grantors you want a reason to notice your organization, connect with you and give you the opportunity to build the relationship.",
                ],
                "q1": "What can your organization offer the people, businesses and grantors you identified that would make them want to stop, pay attention and connect with you?",
                "q1_hint": "Share your first ideas.",
                "deeper_heading": "GIVE THEM A REASON TO COME TO YOU",
                "deeper": [
                    "Think about something genuinely valuable to the audience you want to reach.",
                    "It could be a guide, checklist, report, survey, assessment, educational session, event, community activity, campaign, useful resource, opportunity to share their opinion or invitation to contribute to something meaningful.",
                    "For businesses, it might simply be a reason to open a conversation before asking for sponsorship.",
                    "For grantors, it could begin with understanding what they fund, attending their information sessions, asking good questions and connecting with the people responsible for their funding priorities.",
                    "The first goal is not always to ask for money.",
                    "The first goal is to attract their attention and create the opportunity to build the relationship.",
                ],
                "q2": "What can you offer each audience you identified that is valuable enough to attract their attention and get them to connect with your organization?",
            },
            {
                "id": 4,
                "heading": "HOW WILL YOU RAISE MONEY FROM THEM?",
                "why": [
                    "Once potential funders connect with your organization, you need a clear process for moving that relationship toward financial support.",
                    "You don't raise money by meeting someone for the first time and immediately asking them for money.",
                    "To raise money consistently, you need a process that moves people from knowing your organization to trusting it, giving and continuing the relationship.",
                ],
                "q1": "Once the people, businesses and grantors you identified connect with your organization, how do you think you should raise money from them?",
                "q1_hint": "Share your first thoughts.",
                "deeper_heading": "BUILD THE FUNDRAISING PROCESS",
                "deeper": [
                    "The fundraising process is:",
                    "KNOW → LIKE → TRUST → ASK → FOLLOW UP → STEWARD",
                    "KNOW: They discover your organization and understand what you do.",
                    "LIKE: They stay connected and become interested in the work.",
                    "TRUST: They see your impact, leadership and ability to create the change you promise.",
                    "ASK: You clearly invite them to financially support the mission.",
                    "FOLLOW UP: You continue the conversation when they need more information, time or another interaction.",
                    "STEWARD: You thank them, show them what their support made possible and continue the relationship.",
                    "This is how fundraising becomes a system instead of constantly chasing people and asking strangers for money.",
                ],
                "q2": "Based on what you just learned, what ideas come to mind for how your organization can move potential funders through KNOW, LIKE, TRUST, ASK, FOLLOW UP and STEWARD?",
            },
        ],
        "categories": {
            "people": {"label": "PEOPLE", "question": "Who are the exact types of people with the greatest reason to fund your mission?", "add": "+ Add Another Type Of Person"},
            "businesses": {"label": "BUSINESSES", "question": "What are the exact types of businesses with the greatest reason to support your organization?", "add": "+ Add Another Type Of Business"},
            "grantors": {"label": "GRANTORS", "question": "What are the exact types of grantors with the greatest reason to fund your mission?", "add": "+ Add Another Type Of Grantor"},
        },
        "audience_questions": {
            "2": {"question": "Where can you consistently find them?", "add": "+ Add Another Place"},
            "3": {"question": "What can you offer them that would make them want to connect with your organization?", "add": "+ Add Another Idea"},
            "4": {"question": "", "add": "+ Add Another Idea"},
        },
        "direction": {
            "heading": "YOU BUILT YOUR FUNDRAISING DIRECTION",
            "lines": [
                "You have now decided:",
                "Who should fund your mission.",
                "Where you can consistently find them.",
                "How you can attract their attention.",
                "How you will move them through the fundraising process.",
            ],
            "cta": "Continue",
        },
        "participation_screens": {
            "build_heading": "HOW DO YOU WANT TO HELP BUILD AND MANAGE THE FUNDRAISING SYSTEM?",
            "raise_heading": "HOW DO YOU WANT TO HELP RAISE MONEY?",
            "time_heading": "HOW MUCH TIME CAN YOU REALISTICALLY COMMIT EACH MONTH?",
            "share_heading": "IS THERE ANYTHING ELSE YOU WANT TO SHARE?",
            "share_supporting": "If you have another fundraising idea, opportunity, relationship, concern or way you would like to help that we haven't asked about, share it here.",
            "complete_button": "COMPLETE MY GAME",
        },
        "finetune": {
            "heading": "HERE'S HOW WE UNDERSTOOD YOUR IDEA",
            "your_idea": "YOUR IDEA",
            "fine_tuned": "FINE-TUNED VERSION",
            "use_button": "USE THIS",
            "keep_button": "KEEP MY ORIGINAL IDEA",
        },
    },
}

GAME_V3["guided"] = {
    "label_deeper": "THINK A LITTLE DEEPER",
    "placeholder": "Type your answer here...",
    "refining": "Refining Your Idea...",
    "sections": [
        {"id": 1, "heading": "WHO SHOULD FUND YOUR MISSION?",
         "q1": "Who do you think are the exact types of people, businesses and grantors with the greatest reason to fund your mission?",
         "q2": "Based on what you just learned, who specifically should your organization be looking for?"},
        {"id": 2, "heading": "WHERE CAN YOU CONSISTENTLY FIND THEM?",
         "q1": "Where do you think you can consistently find the people, businesses and grantors you identified?",
         "q2": "Based on that, where should your organization consistently go to find them?"},
        {"id": 3, "heading": "HOW CAN YOU ATTRACT THEIR ATTENTION?",
         "q1": "What can your organization offer the people, businesses and grantors you identified that would make them want to stop, pay attention and connect with you?",
         "q2": "Based on that, what can you offer your potential funders that gives them a reason to move toward your organization before you ask them for money?"},
        {"id": 4, "heading": "HOW WILL YOU RAISE MONEY FROM THEM?",
         "q1": "Once potential funders connect with your organization, how do you think you should raise money from them?",
         "q2": "Based on this process, how should your organization move potential funders from first connection to financial support and an ongoing relationship?"},
    ],
    "direction": {
        "heading": "YOU BUILT YOUR FUNDRAISING DIRECTION",
        "lines": ["You have now identified:", "Who should fund your mission.", "Where you can consistently find them.",
                  "How you can attract their attention.", "How you will move them through your fundraising process."],
        "cta": "CONTINUE",
    },
    "participation_screens": {
        "build_heading": "HOW DO YOU WANT TO HELP BUILD AND MANAGE THE FUNDRAISING SYSTEM?",
        "raise_heading": "HOW DO YOU WANT TO HELP RAISE MONEY?",
        "time_heading": "HOW MUCH TIME CAN YOU REALISTICALLY COMMIT EACH MONTH?",
        "share_heading": "IS THERE ANYTHING ELSE YOU WANT TO SHARE?",
        "share_supporting": "If you have another fundraising idea, opportunity, relationship, concern or way you would like to help that we haven't asked about, share it here.",
        "complete_button": "COMPLETE MY GAME",
    },
    "finetune": {
        "heading": "HERE'S HOW WE UNDERSTOOD YOUR IDEA",
        "your_idea": "YOUR IDEA",
        "fine_tuned": "FINE-TUNED VERSION",
        "use_button": "USE THIS",
        "keep_button": "KEEP MY ORIGINAL",
    },
}
