"""Individual Board Fundraising Game — default section content (admin-overridable via marketing_settings key game_individual_content)."""


def P(text, hint=""):
    return {"text": text, "hint": hint}


GAME_SECTION_DEFAULTS = [
    {
        "id": 1, "key": "who_should_fund", "type": "standard",
        "title": "Who Should Fund Our Mission?",
        "scenario": "Your organisation needs to raise {goal} by {deadline}.\nBefore you can decide how to raise the money, you need to decide who is most likely to fund the work.",
        "first_move_question": "Who do you believe {organisation} should raise money from?",
        "first_move_support": "Think about individuals, businesses and grantmakers. Add every type of funder that comes to mind.",
        "first_move_placeholder": "Example: Parents of children we serve",
        "reveal_label": "Show Me What To Consider",
        "wisdom": "Trying to raise money from everybody usually results in raising money from nobody.\nA strong fundraising strategy identifies the specific groups of individuals, businesses and grantmakers most likely to care about the mission, believe in the outcome and have a reason to support it.",
        "groups": [
            {"key": "individuals", "heading": "Think About Individuals",
             "support": "Read each question and select any that help you identify a type of individual your organisation could raise money from.",
             "kind": "prompts",
             "items": [
                 P("Who benefits when your mission succeeds?", "Think beyond the direct beneficiary. Who else benefits when the problem your organisation solves becomes smaller?"),
                 P("Who would personally want to see the people you serve succeed?"),
                 P("Who wants to help solve the same problem your organisation exists to solve?"),
                 P("Who has experienced or overcome this problem and may want to help someone else?"),
                 P("Who has a personal connection to the people, community or place you serve?"),
                 P("Who already gives time, money, influence or attention to causes similar to yours?"),
                 P("Who has the financial capacity to give and a reason to care about this mission?"),
             ],
             "followup_question": "Knowing what you now know, what other types of individuals come to mind?"},
            {"key": "businesses", "heading": "Think About Businesses", "support": "", "kind": "prompts",
             "items": [
                 P("Which businesses serve the same people or communities your organisation serves?"),
                 P("Which businesses are affected by the problem your organisation is solving?"),
                 P("Which businesses benefit when the people or communities you serve become stronger?"),
                 P("Which businesses publicly support causes, communities or outcomes connected to your mission?"),
                 P("Which businesses want visibility or stronger relationships with the audiences your organisation reaches?"),
                 P("Which businesses already have a relationship with your organisation, board members, staff, volunteers or supporters?"),
             ],
             "followup_question": "What other types of businesses come to mind?"},
            {"key": "grantmakers", "heading": "Think About Grantmakers", "support": "", "kind": "prompts",
             "items": [
                 P("Which grantmakers fund the problem your organisation is working to solve?"),
                 P("Which grantmakers fund the people or population your organisation serves?"),
                 P("Which grantmakers fund organisations working in your location or geographic area?"),
                 P("Which grantmakers fund the specific programme, project or outcome connected to this fundraising goal?"),
             ],
             "followup_question": "What other types of grantmakers come to mind?"},
        ],
        "final_question": "Looking across individuals, businesses and grantmakers, is there anyone else {organisation} should consider raising money from?",
        "complete_label": "Complete This Section",
    },
    {
        "id": 2, "key": "where_to_find", "type": "standard",
        "title": "Where Can We Find Them?",
        "scenario": "Knowing who could fund your mission is only useful if your organisation knows where to find them.",
        "first_move_question": "Where do you believe {organisation} can find the individuals, businesses and grantmakers you identified?",
        "first_move_support": "Add every place that comes to mind.",
        "first_move_placeholder": "Example: Local chamber of commerce",
        "reveal_label": "Show Me What To Consider",
        "wisdom": "Fundraising becomes easier when your organisation stops waiting for funders to find you and intentionally goes where the right funders already gather, work, connect and search for opportunities.",
        "groups": [
            {"key": "places", "heading": "Think Deeper", "support": "Select any of these places worth exploring for your organisation.", "kind": "prompts",
             "items": [
                 P("Your Board's Existing Networks", "Who does your board already know?"),
                 P("Your Staff And Supporter Networks", "Who can your staff, volunteers, donors and supporters introduce?"),
                 P("LinkedIn", "Which individuals, business leaders, corporate decision-makers and funders can be identified or reached through LinkedIn?"),
                 P("Professional And Business Associations", "Which chambers, professional bodies, industry associations or business networks contain people you want to reach?"),
                 P("Community And Local Networks", "Which local groups, community organisations, networking events and civic organisations bring your potential supporters together?"),
                 P("Events And Conferences", "Where do people who care about your mission already gather?"),
                 P("Corporate Websites And Public Information", "Which companies publicly describe community investment, sponsorship or charitable priorities aligned with your work?"),
                 P("Grant Databases And Funder Directories", "Which databases, government portals, foundation directories and funder websites help identify grant opportunities?"),
                 P("Your Existing Donor And Funder Base", "Who can your current donors, sponsors and grantmakers introduce you to?"),
             ],
             "followup_question": "What other places should your organisation look?"},
        ],
        "final_question": "",
        "complete_label": "Complete This Section",
    },
    {
        "id": 3, "key": "attract_attention", "type": "standard",
        "title": "How Will We Attract Their Attention?",
        "scenario": "Finding potential funders is only the beginning. Your organisation needs a reason for them to notice you, become interested and want to know more.",
        "first_move_question": "What can {organisation} do to attract the attention of the people, businesses and grantmakers you identified?",
        "first_move_support": "Add every idea that comes to mind.",
        "first_move_placeholder": "Example: Share impact stories on social media",
        "reveal_label": "Show Me What To Consider",
        "wisdom": "People are more likely to fund an organisation they understand, recognise and trust. Your fundraising strategy needs a consistent way to place your mission, impact and opportunities in front of the right people before asking them for money.",
        "groups": [
            {"key": "ideas", "heading": "Think Deeper", "support": "Select any ideas that could work for your organisation.", "kind": "prompts",
             "items": [
                 P("Share clear stories showing the people and communities being impacted"),
                 P("Publish measurable impact and results"),
                 P("Share useful educational content related to the problem your organisation solves"),
                 P("Use board and supporter networks to make warm introductions"),
                 P("Attend events where potential funders already gather"),
                 P("Build relationships with local and industry media"),
                 P("Create partnerships with respected organisations"),
                 P("Use LinkedIn consistently"),
                 P("Use email communication to educate and engage supporters"),
                 P("Invite potential funders to programmes, events or site visits"),
                 P("Give existing supporters reasons to talk about the organisation"),
                 P("Create opportunities for businesses and individuals to participate before being asked for money"),
             ],
             "followup_question": "What else could help your organisation become visible and attractive to the funders you want to reach?"},
        ],
        "final_question": "",
        "complete_label": "Complete This Section",
    },
    {
        "id": 4, "key": "fundraising_process", "type": "journey",
        "title": "What Process Should We Use To Raise Money?",
        "scenario": "Fundraising works better when people move through a clear relationship process instead of receiving a random request for money.",
        "first_move_question": "From the moment a potential funder first hears about {organisation}, what do you believe should happen before and after they are asked to give?",
        "first_move_support": "",
        "first_move_placeholder": "Share your thinking…",
        "reveal_label": "Show Me What To Consider",
        "wisdom": "A strong fundraising strategy moves people through a clear journey:\nKNOW → LIKE → TRUST → ASK → FOLLOW UP → STEWARD",
        "stages": [
            {"key": "know", "label": "KNOW", "description": "They become aware that your organisation exists."},
            {"key": "like", "label": "LIKE", "description": "They begin connecting with your mission, people and work."},
            {"key": "trust", "label": "TRUST", "description": "They see enough evidence, relationships and credibility to believe in the organisation."},
            {"key": "ask", "label": "ASK", "description": "They receive a clear opportunity to financially support the mission."},
            {"key": "follow_up", "label": "FOLLOW UP", "description": "The organisation continues the conversation instead of treating one request as the end."},
            {"key": "steward", "label": "STEWARD", "description": "Supporters are thanked, updated, engaged and shown what their support is making possible."},
        ],
        "stages_question": "What should {organisation} do at each stage of this journey?",
        "groups": [],
        "final_question": "",
        "complete_label": "Complete This Section",
    },
    {
        "id": 5, "key": "technology", "type": "standard",
        "title": "What Technology Do We Need?",
        "scenario": "A fundraising strategy becomes difficult to execute at scale when relationships, communication and follow-up depend entirely on people's memory.",
        "first_move_question": "What technology do you believe {organisation} needs to execute its fundraising strategy effectively?",
        "first_move_support": "Add every tool or system that comes to mind.",
        "first_move_placeholder": "Example: A donor database",
        "reveal_label": "Show Me What To Consider",
        "wisdom": "Technology should help your organisation identify opportunities, manage relationships, communicate consistently, track activity and make sure important fundraising actions do not fall through the cracks.",
        "groups": [
            {"key": "categories", "heading": "Think Deeper", "support": "Which of these does your organisation need?", "kind": "prompts",
             "items": [
                 P("CRM or donor management system"),
                 P("Email marketing system"),
                 P("Online donation/payment platform"),
                 P("Prospect research tools"),
                 P("Grant research/tracking tools"),
                 P("Corporate prospect tracking"),
                 P("Project and task management"),
                 P("Meeting/calendar scheduling"),
                 P("Document/material storage"),
                 P("Social media/content tools"),
                 P("AI tools that help research, draft or organise fundraising work"),
                 P("Reporting/dashboard tools"),
             ],
             "followup_question": "Is there anything else you would add?"},
        ],
        "final_question": "",
        "complete_label": "Complete This Section",
    },
    {
        "id": 6, "key": "team", "type": "standard",
        "title": "Who Do We Need On The Fundraising Team?",
        "scenario": "A fundraising strategy needs people who are responsible for making it happen.",
        "first_move_question": "Who do you believe needs to be involved in executing {organisation}'s fundraising strategy?",
        "first_move_support": "Add every person or role that comes to mind.",
        "first_move_placeholder": "Example: A volunteer grant writer",
        "reveal_label": "Show Me What To Consider",
        "wisdom": "Your fundraising team does not have to be made entirely of paid fundraising staff. It can include staff, board members, volunteers, consultants and specialists who each take responsibility for specific parts of the system.",
        "groups": [
            {"key": "roles", "heading": "Think Deeper", "support": "Select the roles your organisation would need.", "kind": "prompts",
             "items": [
                 P("Fundraising lead"),
                 P("Executive leadership"),
                 P("Board members"),
                 P("Individual giving lead"),
                 P("Major donor lead"),
                 P("Corporate partnership/sponsorship lead"),
                 P("Grant writer or grant lead"),
                 P("Donor stewardship lead"),
                 P("Communications/content support"),
                 P("Events support"),
                 P("Prospect research support"),
                 P("CRM/data management"),
                 P("Volunteer fundraising support"),
                 P("Administrative/project coordination"),
             ],
             "followup_question": "Who else would your organisation need to execute this strategy well?"},
        ],
        "final_question": "",
        "complete_label": "Complete This Section",
    },
    {
        "id": 7, "key": "materials", "type": "standard",
        "title": "What Materials And Tools Do We Need?",
        "scenario": "People cannot execute a fundraising strategy effectively if they do not have the materials required to communicate the mission, make the case and follow up.",
        "first_move_question": "What fundraising materials do you believe {organisation} needs?",
        "first_move_support": "Add every material that comes to mind.",
        "first_move_placeholder": "Example: A sponsorship proposal",
        "reveal_label": "Show Me What To Consider",
        "wisdom": "Fundraising materials should make it easier for the people executing the strategy to explain the mission, demonstrate impact, present an opportunity, make an ask and continue the relationship.",
        "groups": [
            {"key": "materials", "heading": "Think Deeper", "support": "Select the materials your organisation needs.", "kind": "prompts",
             "items": [
                 P("Case for Support"),
                 P("Organisation overview"),
                 P("Impact stories"),
                 P("Impact statistics"),
                 P("Donor presentation/deck"),
                 P("Corporate sponsorship or partnership proposal"),
                 P("Grant boilerplate/core organisational information"),
                 P("Introduction email templates"),
                 P("Fundraising outreach emails"),
                 P("Follow-up templates"),
                 P("Ask scripts"),
                 P("Donor meeting talking points"),
                 P("Online donation page"),
                 P("Campaign page"),
                 P("Social media fundraising content"),
                 P("Thank-you templates"),
                 P("Donor stewardship materials"),
                 P("Board fundraising toolkit"),
                 P("Event materials"),
             ],
             "followup_question": "What other materials would help your fundraising team execute?"},
        ],
        "final_question": "",
        "complete_label": "Complete This Section",
    },
    {
        "id": 8, "key": "timeline", "type": "stages",
        "title": "What Should Our Execution Timeline Look Like?",
        "scenario": "A fundraising strategy becomes real when it is connected to actions and deadlines.",
        "first_move_question": "What do you believe {organisation} should accomplish first, and what should happen after that?",
        "first_move_support": "Add the actions that come to mind, in any order.",
        "first_move_placeholder": "Example: Build our donor database",
        "reveal_label": "Show Me What To Consider",
        "wisdom": "Your organisation does not need to do everything at once. A good execution timeline builds the fundraising system first, launches priority fundraising activity and then creates a rhythm of outreach, follow-up and stewardship.",
        "stages": [
            {"key": "set_up", "label": "SET UP", "description": "What needs to be built or prepared before major fundraising activity begins?"},
            {"key": "launch", "label": "LAUNCH", "description": "What fundraising activity should begin first?"},
            {"key": "execute", "label": "EXECUTE", "description": "What should happen consistently once fundraising begins?"},
            {"key": "review", "label": "REVIEW AND IMPROVE", "description": "How often should the organisation review results and adjust the strategy?"},
        ],
        "stages_question": "Add the actions you believe belong in each stage.",
        "groups": [],
        "final_question": "",
        "complete_label": "Complete This Section",
    },
    {
        "id": 9, "key": "system_building", "type": "preferences",
        "title": "How Do You Want To Help Build The Fundraising System?",
        "scenario": "Board members can help fundraising without personally asking everyone they know for money. One important role is helping the organisation build the system that makes fundraising possible.",
        "first_move_question": "How would you personally like to help {organisation} build its fundraising system?",
        "first_move_support": "Select everything that interests you.",
        "options": [
            "Help recruit people for the fundraising team",
            "Help identify potential fundraising volunteers",
            "Help manage or coordinate part of the fundraising team",
            "Help research potential funders",
            "Help identify corporate prospects",
            "Help identify grant opportunities",
            "Help develop fundraising materials",
            "Help develop the Case for Support",
            "Help create corporate partnership materials",
            "Help improve fundraising technology",
            "Help select or oversee the CRM/donor system",
            "Help organise fundraising data",
            "Help develop fundraising processes",
            "Help with communications/content",
            "Help plan fundraising events",
            "Help monitor execution/accountability",
            "Help review fundraising performance",
            "Other",
        ],
        "note_question": "How would you like to help with this?",
        "involvement_question": "For the areas you selected, how would you describe your involvement?",
        "involvement_options": ["I can lead", "I can actively support", "I can advise when needed"],
        "wisdom": "",
        "groups": [],
        "final_question": "",
        "complete_label": "Complete This Section",
    },
    {
        "id": 10, "key": "direct_fundraising", "type": "preferences",
        "title": "How Do You Want To Help Raise Money?",
        "scenario": "The second way board members can help is by participating directly in fundraising activities in ways that fit their relationships, confidence and strengths.",
        "first_move_question": "How would you personally like to help {organisation} raise money?",
        "first_move_support": "Select everything that interests you.",
        "options": [
            "Identify potential donors",
            "Identify potential businesses/corporate partners",
            "Identify potential grant opportunities",
            "Make introductions",
            "Invite potential funders to meetings or events",
            "Help cultivate relationships before an ask",
            "Attend donor meetings",
            "Attend corporate sponsor/partner meetings",
            "Personally make the ask",
            "Participate in an ask with someone else",
            "Follow up with potential funders",
            "Steward existing donors",
            "Steward corporate partners",
            "Thank supporters",
            "Organise or support fundraising events",
            "Promote fundraising through my social media",
            "Promote fundraising through my professional network",
            "Share fundraising campaigns with people I know",
            "Host a small fundraising gathering",
            "Other",
        ],
        "note_question": "Tell us anything about how you would like to help.",
        "do_not_want_question": "Is there anything you would prefer NOT to do?",
        "wisdom": "",
        "groups": [],
        "final_question": "",
        "complete_label": "Complete My Individual Game",
    },
]

EDITABLE_FIELDS = ["title", "scenario", "first_move_question", "first_move_support", "wisdom", "complete_label", "final_question"]


def merged_sections(stored: dict) -> list:
    """stored = {"<id>": {field overrides, "group_items": {group_key: [{text,hint}]}}}"""
    sections = []
    for default in GAME_SECTION_DEFAULTS:
        override = (stored or {}).get(str(default["id"]), {})
        section = {**default}
        for field in EDITABLE_FIELDS:
            if isinstance(override.get(field), str) and override[field].strip():
                section[field] = override[field]
        group_items = override.get("group_items") or {}
        if group_items and section.get("groups"):
            section["groups"] = [
                {**group, "items": group_items[group["key"]]} if isinstance(group_items.get(group["key"]), list) and group_items[group["key"]] else group
                for group in section["groups"]
            ]
        sections.append(section)
    return sections
