"""Board Fundraising Game — Individual Game content (Version 2, Phase 7 rebuild).
Stable strategy keys preserved. Zero AI. merged_sections keeps admin content overrides working."""

INDIVIDUAL_GAME_VERSION = 2


def C(text, hint=""):
    return {"text": text, "hint": hint}


GAME_SECTION_DEFAULTS = [
    {
        "id": 1, "key": "who_should_fund", "type": "discover",
        "title": "Who Should Fund Our Mission?",
        "scenario": "{organisation} wants to raise {goal} by {deadline}.\n\nBefore you decide how to raise the money, you need to identify the types of people, businesses and grantmakers most likely to care about what your organisation is trying to accomplish.",
        "first_move_question": "Without overthinking it, who do you believe {organisation} should raise money from?",
        "first_move_support": "Think about individuals, businesses and grantmakers. Add every type of funder that immediately comes to mind.",
        "first_placeholder": "Example: Local business owners", "first_add_label": "Add Idea",
        "wisdom": "Trying to raise money from everybody usually results in raising money from nobody.\n\nA strong fundraising strategy begins by identifying the specific groups of individuals, businesses and grantmakers most likely to care about the mission, believe in the outcome and have a reason to support it.\n\nLet's look at each group differently.",
        "wisdom_button": "Think About Individuals",
        "groups": [
            {"key": "individuals", "heading": "Who Are The Individuals Most Likely To Care?",
             "support": "Read these seven questions slowly. You do not need an answer to every question. Their purpose is to help you notice groups of people you may not have considered before.",
             "kind": "prompts", "ask": "What Types Of Individuals Come To Mind Now?",
             "ask_support": "Add the types of individuals these questions made you think about.",
             "placeholder": "Example: Former programme participants who are now successful professionals",
             "add_label": "Add Individual Audience", "next_label": "Continue To Businesses",
             "items": [
                 C("Who benefits when your mission succeeds?", "Think beyond the people directly receiving your service. Who else benefits when this problem is solved or reduced?"),
                 C("Who would personally want to see the people your organisation serves succeed?"),
                 C("Which types of people already care about solving the same problem your organisation exists to solve?"),
                 C("Who has personally experienced, overcome or been affected by this problem and may want to help someone else?"),
                 C("Who has a personal, family, professional or community connection to the people your organisation serves?"),
                 C("Who benefits socially, professionally or economically when the people or community you serve become stronger?"),
                 C("Who already gives money, time, influence or attention to causes similar to yours?"),
             ]},
            {"key": "businesses", "heading": "Which Businesses Have A Reason To Care?", "support": "",
             "kind": "prompts", "ask": "What Types Of Businesses Come To Mind?",
             "ask_support": "Add business types, industries or groups of companies. You do not need specific company names unless one naturally comes to mind.",
             "placeholder": "Example: Local construction companies",
             "add_label": "Add Business Audience", "next_label": "Continue To Grantmakers",
             "items": [
                 C("Which businesses serve the same people or communities your organisation serves?"),
                 C("Which businesses are affected by the problem your organisation is helping solve?"),
                 C("Which businesses benefit when the people or communities your organisation serves become stronger?"),
                 C("Which businesses have community, social-impact or charitable priorities connected to your mission?"),
                 C("Which businesses want stronger visibility or relationships with the audiences and communities your organisation reaches?"),
                 C("Which businesses already have a relationship with your organisation, board members, staff, volunteers, donors or supporters?"),
             ]},
            {"key": "grantmakers", "heading": "Which Grantmakers Are Most Likely To Fit?", "support": "",
             "kind": "prompts", "ask": "What Types Of Grantmakers Come To Mind?", "ask_support": "",
             "placeholder": "Example: Foundations funding youth employment",
             "add_label": "Add Grantmaker Audience", "next_label": "Continue",
             "items": [
                 C("Which grantmakers fund the problem your organisation is working to solve?"),
                 C("Which grantmakers fund the people or population your organisation serves?"),
                 C("Which grantmakers fund organisations working in your location or geographic area?"),
                 C("Which grantmakers fund the programme, project or outcome connected to this fundraising goal?"),
             ]},
        ],
        "final_question": "Knowing what you now know, is there any other type of individual, business or grantmaker {organisation} should consider raising money from?",
        "final_heading": "Anyone Else?",
        "complete_label": "Complete This Section",
    },
    {
        "id": 2, "key": "where_to_find", "type": "discover", "extra": "connect_audiences",
        "title": "Where Can We Find Them?",
        "scenario": "You have identified the types of people, businesses and grantmakers that could help fund {organisation}.\n\nThe next question is simple: where can your organisation actually find them?",
        "first_move_heading": "Where Would You Look First?",
        "first_move_question": "If you had to start finding potential funders today, where would you look?",
        "first_move_support": "",
        "first_placeholder": "Example: LinkedIn", "first_add_label": "Add Place Or Channel",
        "wisdom": "Knowing who should fund your mission is only useful when you know where those people can be found.\n\nStrong fundraising strategies deliberately identify the networks, platforms, communities, databases, events and relationships where the right funders already exist.",
        "wisdom_button": "Show Me Where To Look",
        "groups": [
            {"key": "places", "heading": "Think About Where Your Funders Already Are", "support": "",
             "kind": "prompts", "ask": "What Places Or Channels Come To Mind Now?", "ask_support": "",
             "placeholder": "Example: Local chamber of commerce", "add_label": "Add Place Or Channel", "next_label": "Continue",
             "items": [
                 C("Your Board's Networks", "Who do board members already know personally or professionally?"),
                 C("Staff, Volunteer And Supporter Networks", "Who could people already connected to your organisation introduce?"),
                 C("LinkedIn And Professional Networks", "Where can you find individuals, executives, business leaders and potential partners professionally?"),
                 C("Business Networks", "Which chambers, industry groups, business associations and networking communities contain businesses you want to reach?"),
                 C("Community Networks", "Which local organisations, civic groups, community associations and local events bring potential supporters together?"),
                 C("Events And Conferences", "Where do people interested in your mission, population or sector already gather?"),
                 C("Corporate Websites And Public Information", "Which companies publicly describe sponsorship, community investment or social-impact priorities?"),
                 C("Grant Databases And Funder Directories", "Where can you identify grantmakers whose priorities match your mission, population, geography or project?"),
                 C("Existing Donors And Funders", "Who could your current donors, partners and grantmakers introduce your organisation to?"),
                 C("Similar Organisations", "Where are organisations similar to yours finding donors, sponsors and grantmakers?"),
             ]},
        ],
        "connect_heading": "Connect The People To The Places",
        "connect_support": "For any audience where you already know where to find them, connect them now.",
        "final_question": "Is there anywhere else {organisation} should look for potential funders?",
        "final_heading": "Anywhere Else?",
        "complete_label": "Complete This Section",
    },
    {
        "id": 3, "key": "attract_attention", "type": "discover", "extra": "audience_tags",
        "title": "How Will We Attract Their Attention?",
        "scenario": "Finding potential funders does not mean they will automatically care about your organisation.\n\nYour next challenge is getting the right people to notice the mission, understand why it matters and want to know more.",
        "first_move_heading": "What Would Make Potential Funders Pay Attention To {organisation}?",
        "first_move_question": "What would make potential funders pay attention to {organisation}?",
        "first_move_support": "Add anything you believe could make the organisation more visible, interesting or relevant to the people you want to reach.",
        "first_placeholder": "Example: Share success stories from our programmes", "first_add_label": "Add Idea",
        "wisdom": "People are more likely to fund organisations they understand, recognise and trust.\n\nBefore asking for money, your organisation needs consistent ways to place its mission, impact and opportunities in front of the people most likely to care.",
        "wisdom_button": "Think Deeper",
        "groups": [
            {"key": "ideas", "heading": "Think Deeper", "support": "",
             "kind": "prompts", "ask": "What Attraction Ideas Come To Mind Now?", "ask_support": "",
             "placeholder": "Example: Invite business leaders to visit a programme", "add_label": "Add Attraction Idea", "next_label": "Continue",
             "items": [
                 C("Tell Stories", "How can real stories show the human impact of your work?"),
                 C("Show Results", "What outcomes, numbers or evidence demonstrate that the organisation is making a difference?"),
                 C("Teach", "What useful information can your organisation share about the problem it exists to solve?"),
                 C("Use Warm Introductions", "Who can introduce your organisation to people who already trust them?"),
                 C("Be Present Where Funders Gather", "Which events, meetings, networks and communities should your organisation participate in?"),
                 C("Invite People Into The Work", "Could potential funders visit, attend an event, volunteer, observe a programme or meet the people behind the mission?"),
                 C("Build Partnerships", "Which respected organisations or businesses could increase your visibility and credibility?"),
                 C("Communicate Consistently", "How can email, LinkedIn, social media or other communication keep your work visible over time?"),
                 C("Give Supporters Something To Share", "What stories, campaigns, events or opportunities would make existing supporters want to tell others about the organisation?"),
             ]},
        ],
        "final_question": "What else could help {organisation} become visible, relevant and attractive to potential funders?",
        "final_heading": "Anything Else?",
        "complete_label": "Complete This Section",
    },
    {
        "id": 4, "key": "fundraising_process", "type": "journey",
        "title": "What Process Should We Use To Raise Money?",
        "scenario": "Fundraising becomes unpredictable when the organisation simply finds people and immediately asks them for money.\n\nA strong fundraising system gives potential funders a journey from first discovering your organisation to becoming long-term supporters.",
        "first_move_heading": "Imagine You Meet A Potential Funder Today",
        "first_move_question": "What do you think should happen between the moment they first hear about {organisation} and the moment they become a committed supporter?",
        "first_move_support": "", "first_mode": "text", "first_lock_label": "Lock In My First Answer",
        "wisdom": "A strong fundraising relationship usually moves through six stages:\n\nKNOW → LIKE → TRUST → ASK → FOLLOW UP → STEWARD\n\nThe exact actions will differ by funder, but the organisation should know what it wants to happen at every stage.",
        "wisdom_button": "Build The Journey",
        "stages": [
            {"key": "know", "label": "KNOW", "number": 1, "description": "They discover that your organisation exists.",
             "ask": "What should {organisation} do to make potential funders aware of the organisation?",
             "prompt": "Think about introductions, events, content, partnerships, social media, publicity and places your funders already gather."},
            {"key": "like", "label": "LIKE", "number": 2, "description": "They begin connecting with your mission, people and work.",
             "ask": "What should help them become interested in and emotionally connected to the mission?", "prompt": ""},
            {"key": "trust", "label": "TRUST", "number": 3, "description": "They gain enough confidence to believe the organisation can create meaningful impact.",
             "ask": "What should {organisation} show or do to build trust?",
             "prompt": "Think about results, stories, leadership, transparency, credibility, relationships and evidence of impact."},
            {"key": "ask", "label": "ASK", "number": 4, "description": "They receive a clear opportunity to financially support the mission.",
             "ask": "How should {organisation} present the opportunity and ask for support?", "prompt": ""},
            {"key": "follow_up", "label": "FOLLOW UP", "number": 5, "description": "One conversation or one request should not be the end of the relationship.",
             "ask": "What should happen after an ask, whether the funder says yes, maybe or not yet?", "prompt": ""},
            {"key": "steward", "label": "STEWARD", "number": 6, "description": "Supporters should continue seeing the value and impact of their relationship with your organisation.",
             "ask": "How should {organisation} thank, update, involve and retain its supporters?", "prompt": ""},
        ],
        "final_heading": "Your Final Process",
        "complete_label": "Complete This Section", "groups": [],
    },
    {
        "id": 5, "key": "technology", "type": "discover", "situation_context": "technology",
        "title": "What Technology Do We Need To Execute At Scale?",
        "scenario": "Fundraising becomes difficult to scale when relationships, tasks, communication and follow-up depend entirely on people's memory.",
        "first_move_question": "What technology do you believe {organisation} needs to execute its fundraising strategy effectively?",
        "first_move_support": "", "context_heading": "What Your Organisation Already Uses",
        "first_placeholder": "Example: A donor database", "first_add_label": "Add Technology Need",
        "wisdom": "Fundraising technology should make it easier to find opportunities, manage relationships, communicate consistently, track activity and make sure important actions do not fall through the cracks.",
        "wisdom_button": "Think About What The System Needs To Do",
        "groups": [
            {"key": "categories", "heading": "Think About What The System Needs To Do", "support": "",
             "kind": "prompts", "ask": "What Technology Capabilities Does The Organisation Need?",
             "ask_support": "You can enter a technology function, a category, or a specific tool you already know.",
             "placeholder": "Example: A way to track corporate outreach", "add_label": "Add Technology Capability", "next_label": "Continue",
             "items": [
                 C("Manage Relationships", "How will the organisation keep donor, sponsor and prospect information in one place?"),
                 C("Find Prospects", "What will help identify individuals, businesses and funders that match the strategy?"),
                 C("Communicate", "What will help the organisation send consistent email, updates and fundraising communication?"),
                 C("Accept Donations", "How will supporters give online and how will gifts be recorded?"),
                 C("Manage Grants", "How will the organisation research opportunities, track deadlines and monitor applications?"),
                 C("Track Corporate Outreach", "How will corporate prospects, conversations and follow-ups be managed?"),
                 C("Manage Tasks", "How will the fundraising team know what needs to happen, who owns it and when it is due?"),
                 C("Schedule Meetings", "How will funders and fundraising team members easily schedule conversations?"),
                 C("Store Materials", "Where will fundraising documents and materials live so the team can access the right version?"),
                 C("Measure Performance", "How will the organisation track fundraising activity and results?"),
                 C("Use AI Wisely", "Where could AI help the team research, organise, draft or prepare without replacing human relationships and decisions?"),
             ]},
        ],
        "final_question": "Is there anything else the fundraising system needs technology to help the organisation do?",
        "final_heading": "Anything Else?",
        "complete_label": "Complete This Section",
    },
    {
        "id": 6, "key": "team", "type": "discover", "extra": "role_fillers", "situation_context": "team",
        "title": "Who Do We Need On The Fundraising Team?",
        "scenario": "A fundraising strategy only works when real people are responsible for executing it.\n\nThose people do not all need to be paid fundraisers.",
        "first_move_question": "Who or what roles do you believe {organisation} needs on its fundraising team?",
        "first_move_support": "", "context_heading": "Who Is Already Involved",
        "first_placeholder": "Example: Someone to coordinate fundraising", "first_add_label": "Add Role",
        "wisdom": "A strong fundraising team can include staff, board members, volunteers, consultants and specialists.\n\nThe important question is whether every important part of the fundraising system has someone responsible for making it happen.",
        "wisdom_button": "Think About The Work That Needs An Owner",
        "groups": [
            {"key": "roles", "heading": "Think About The Work That Needs An Owner", "support": "",
             "kind": "prompts", "ask": "What Roles Does Your Organisation Need?", "ask_support": "",
             "placeholder": "Example: Grants coordinator", "add_label": "Add Role", "next_label": "Continue",
             "items": [
                 C("Fundraising Leadership", "Who will coordinate the overall strategy and keep execution moving?"),
                 C("Executive Leadership", "Who provides organisational leadership, credibility and high-level relationships?"),
                 C("Board Members", "Where can board members use their networks, expertise and influence?"),
                 C("Prospect Research", "Who will help identify and qualify potential funders?"),
                 C("Individual Giving", "Who will help cultivate and manage relationships with individual donors?"),
                 C("Corporate Partnerships", "Who will identify, cultivate and manage business relationships?"),
                 C("Grants", "Who will research, write, submit and manage grant opportunities?"),
                 C("Donor Stewardship", "Who will make sure supporters are thanked, updated and retained?"),
                 C("Communications And Content", "Who will create the stories, updates and materials fundraising depends on?"),
                 C("Events", "Who will plan and support fundraising events when events are part of the strategy?"),
                 C("CRM And Data", "Who will maintain fundraising records, activity and relationship data?"),
                 C("Project Coordination", "Who will track deadlines, responsibilities and follow-up across the fundraising team?"),
             ]},
        ],
        "filler_question": "Who could fill this role?",
        "filler_options": ["Staff", "Board member", "Volunteer", "Consultant/external specialist", "Not sure yet"],
        "final_question": "Is any important fundraising responsibility still missing an owner?",
        "final_heading": "Anything Missing?",
        "complete_label": "Complete This Section",
    },
    {
        "id": 7, "key": "materials", "type": "discover", "extra": "material_status", "situation_context": "materials",
        "title": "What Materials And Tools Do We Need To Execute?",
        "scenario": "Even a strong fundraising team will struggle if people do not have the materials they need to explain the mission, demonstrate impact, make the case and follow up.",
        "first_move_question": "What fundraising materials do you believe {organisation} needs to execute this strategy?",
        "first_move_support": "", "context_heading": "Materials Your Organisation Already Has",
        "first_placeholder": "Example: A one-page organisation overview", "first_add_label": "Add Material",
        "wisdom": "Fundraising materials should make it easier for everyone executing the strategy to tell the same story, explain the opportunity, make an ask and continue the relationship.",
        "wisdom_button": "See What Your Team May Need",
        "groups": [
            {"key": "materials", "heading": "See What Your Team May Need",
             "support": "Tap any material to add it to your ideas.",
             "kind": "select", "ask": "What Else Does Your Fundraising Team Need?", "ask_support": "",
             "placeholder": "Example: A programme tour invitation pack", "add_label": "Add Material", "next_label": "Continue",
             "items": [C(label) for label in [
                 "Case for Support", "Organisation Overview / One-Pager", "Impact Stories", "Impact Statistics",
                 "Impact Report", "Donor Presentation", "Corporate Partnership or Sponsorship Deck", "Partnership Offer",
                 "Grant Boilerplate / Core Organisational Narrative", "Introduction Email Templates", "Fundraising Outreach Emails",
                 "Follow-Up Templates", "Ask Scripts", "Donor Meeting Talking Points", "Corporate Meeting Talking Points",
                 "Online Donation Page", "Campaign Page", "Social Media Fundraising Content", "Thank-You Templates",
                 "Donor Stewardship Materials", "Corporate Partner Stewardship Materials", "Board Fundraising Toolkit", "Event Materials",
             ]]},
        ],
        "status_heading": "Existing Vs Needed",
        "status_options": ["Already Have — Keep Using", "Already Have — Needs Improvement", "Need To Create"],
        "final_heading": "Your Final Ideas",
        "final_question": "",
        "complete_label": "Complete This Section",
    },
    {
        "id": 8, "key": "timeline", "type": "stages",
        "title": "What Should Our Execution Timeline Look Like?",
        "scenario": "{organisation} wants to raise {goal} by {deadline}.\n\nA strategy becomes real when the board can see what needs to happen first, what should launch next and what must continue until the goal is reached.",
        "first_move_heading": "If You Were Leading This Strategy, What Would You Do First?",
        "first_move_question": "If you were leading this strategy, what would you do first?",
        "first_move_support": "Add the actions you believe should happen first or early in the fundraising effort.",
        "first_placeholder": "Example: Build a corporate prospect list", "first_add_label": "Add Action",
        "wisdom": "Your organisation does not need to do everything at once.\n\nA strong execution timeline builds what is needed, launches the highest-priority fundraising activity, creates a consistent execution rhythm and regularly reviews what is working.\n\nSET UP → LAUNCH → EXECUTE → REVIEW & IMPROVE",
        "wisdom_button": "Build The Timeline",
        "stages": [
            {"key": "set_up", "label": "SET UP", "number": 1,
             "description": "What must be built, organised or prepared before major fundraising activity begins?",
             "ask": "What must be built, organised or prepared before major fundraising activity begins?",
             "prompt": "Think about: team, technology, prospect lists, materials, processes, roles and responsibilities."},
            {"key": "launch", "label": "LAUNCH", "number": 2,
             "description": "What fundraising activity should begin once the basic system is ready?",
             "ask": "What fundraising activity should begin once the basic system is ready?", "prompt": ""},
            {"key": "execute", "label": "EXECUTE", "number": 3,
             "description": "What should the fundraising team do consistently once fundraising activity begins?",
             "ask": "What should the fundraising team do consistently once fundraising activity begins?", "prompt": ""},
            {"key": "review", "label": "REVIEW & IMPROVE", "number": 4,
             "description": "How should the organisation review results, hold people accountable and improve the strategy as it executes?",
             "ask": "How should the organisation review results, hold people accountable and improve the strategy as it executes?", "prompt": ""},
        ],
        "timing_question": "When should this happen?",
        "timing_options": ["Immediately", "First 30 Days", "Days 31–60", "Days 61–90", "Later", "Before Fundraising Deadline"],
        "final_heading": "Your Final Timeline",
        "complete_label": "Complete This Section", "groups": [],
    },
    {
        "id": 9, "key": "system_building", "participation_key": "system_building_participation", "type": "preferences",
        "title": "How Do You Want To Help Build The Fundraising System?",
        "scenario": "Board members do not have to personally ask everyone they know for money to make a major contribution to fundraising.\n\nOne powerful way to help is by building the people, processes, technology, materials and accountability system that makes fundraising possible.",
        "situation_button": "Show Me The Ways I Can Help",
        "choose_heading": "Where Would You Like To Contribute?",
        "choose_support": "Choose every area where you would genuinely be willing to help.",
        "groups": [
            {"key": "people_team", "heading": "PEOPLE & TEAM", "items": [C("Recruit people for the fundraising team"), C("Identify potential fundraising volunteers"), C("Manage or coordinate part of the fundraising team")]},
            {"key": "research", "heading": "RESEARCH & OPPORTUNITIES", "items": [C("Research potential funders"), C("Identify corporate prospects"), C("Identify grant opportunities")]},
            {"key": "materials_comm", "heading": "MATERIALS & COMMUNICATION", "items": [C("Develop fundraising materials"), C("Develop the Case for Support"), C("Create corporate partnership materials"), C("Support communications/content")]},
            {"key": "tech_data", "heading": "TECHNOLOGY & DATA", "items": [C("Improve fundraising technology"), C("Select or oversee the CRM/donor system"), C("Organise fundraising data")]},
            {"key": "process", "heading": "PROCESS & EXECUTION", "items": [C("Develop fundraising processes"), C("Plan fundraising events"), C("Monitor execution/accountability"), C("Review fundraising performance")]},
            {"key": "other", "heading": "OTHER", "items": [C("Other")]},
        ],
        "involvement_question": "How would you like to be involved?",
        "involvement_options": ["I can lead this", "I can actively support this", "I can advise when needed"],
        "note_question": "Anything you want the organisation to know about how you can help?",
        "review_heading": "Your Role In Building The Fundraising System",
        "custom_question": "Is there another way you would like to help build the fundraising system?",
        "complete_label": "Complete This Section",
    },
    {
        "id": 10, "key": "direct_fundraising", "participation_key": "direct_fundraising_participation", "type": "preferences",
        "title": "How Do You Want To Help Raise Money?",
        "scenario": "The second way board members can help is by participating directly in fundraising activities that fit their relationships, confidence and strengths.\n\nYou do not have to choose everything. Choose the ways you are genuinely willing to participate.",
        "situation_button": "Choose How I Want To Help",
        "choose_heading": "Choose Your Fundraising Activities",
        "choose_support": "Choose every activity you are genuinely willing to participate in.",
        "groups": [
            {"key": "find", "heading": "FIND OPPORTUNITIES", "items": [C("Identify potential donors"), C("Identify potential businesses/corporate partners"), C("Identify potential grant opportunities")]},
            {"key": "doors", "heading": "OPEN DOORS", "items": [C("Make introductions"), C("Invite potential funders to meetings or events"), C("Share fundraising campaigns with people I know"), C("Promote fundraising through my professional network")]},
            {"key": "relationships", "heading": "BUILD RELATIONSHIPS", "items": [C("Help cultivate relationships before an ask"), C("Attend donor meetings"), C("Attend corporate sponsor/partner meetings"), C("Follow up with potential funders")]},
            {"key": "ask", "heading": "MAKE THE ASK", "items": [C("Personally make the ask"), C("Participate in an ask with someone else")]},
            {"key": "steward", "heading": "STEWARD SUPPORTERS", "items": [C("Steward existing donors"), C("Steward corporate partners"), C("Thank supporters")]},
            {"key": "events", "heading": "EVENTS & VISIBILITY", "items": [C("Organise or support fundraising events"), C("Promote fundraising through my social media"), C("Host a small fundraising gathering")]},
            {"key": "other", "heading": "OTHER", "items": [C("Other")]},
        ],
        "note_question": "Anything you want the organisation to know about how you would like to help with this?",
        "do_not_want_heading": "Is There Anything You Would Prefer Not To Do?",
        "do_not_want_support": "Being clear about this helps the organisation give you a role that fits your strengths instead of assigning fundraising activities you are uncomfortable with.",
        "do_not_want_none": "None — I do not need to exclude anything",
        "review_heading": "How You Want To Help Raise Money",
        "complete_label": "Complete My Individual Game",
    },
]

EDITABLE_FIELDS = ["title", "scenario", "first_move_question", "first_move_support", "wisdom", "complete_label",
                   "final_question", "wisdom_button", "first_move_heading", "final_heading",
                   "choose_heading", "choose_support", "note_question", "involvement_question",
                   "do_not_want_heading", "do_not_want_support", "custom_question"]


def merged_sections(stored: dict) -> list:
    """stored = {"<id>": {field overrides, "group_items": {group_key: [{text,hint}]}}}"""
    sections = []
    for default in GAME_SECTION_DEFAULTS:
        override = (stored or {}).get(str(default["id"]), {})
        section = {**default}
        for field in EDITABLE_FIELDS:
            if isinstance(override.get(field), str) and override[field].strip():
                section[field] = override[field]
        group_items = override.get("group_items") or {}
        if group_items and section.get("groups"):
            section["groups"] = [
                {**group, "items": group_items[group["key"]]} if isinstance(group_items.get(group["key"]), list) and group_items[group["key"]] else group
                for group in section["groups"]
            ]
        sections.append(section)
    return sections
