"""Active learning narration library, Rooney Akpesiri LIVE ElevenLabs voice.
Scripts are word-for-word and must not be rewritten. Older narration audio stays stored but inactive."""

TEXTS = {
    "lead_opening": "Welcome.\nNow let's build your organization's fundraising strategy.\nBefore we go ahead, there is something very important I want you to understand.\nTo raise money consistently and exponentially, you need to build your organization's fundraising system.\nBasically, a system that runs consistently to bring in money for your organization.\nAnd your fundraising system is made up of two parts.\nThe first is your fundraising strategy.\nYour fundraising strategy identifies the exact type of people, businesses and grantors meant to fund your mission, where to consistently find them, how to attract them and the step-by-step process to raise money from them.\nThen you identify the people, technology, materials, resources and content you need to execute that strategy.\nThe second part is the actual system that runs that strategy consistently.\nThat's where technology, your board, volunteers, staff or a fundraising team can actually help you execute.\nIn this game, we're starting with the foundation, your fundraising strategy.\nAnd we're going to build it around the fundraising goal you can see on your screen.\nBy the time you're done, you will understand what it takes to raise money and build your organization's fundraising system.\nAnd your ideas will become part of the strategy your organization can use to reach this fundraising goal.\nDon't worry about trying to give perfect answers.\nI'm going to walk you through it one step at a time.\nReady?\nLet's get started.",
    "board_opening": "Welcome.\nYou are about to help your organization build its fundraising strategy.\nAnd before we start, I want you to understand why your ideas matter.\nTo raise money consistently and exponentially, your organization needs a fundraising system.\nAnd the foundation of that system is the fundraising strategy.\nThat's where you identify the exact type of people, businesses and grantors meant to fund the mission, where to find them, how to attract them and the process to raise money from them.\nNow, one person can sit down and try to figure all this out alone.\nBut the strategy will only be as strong as that person's ideas and experience.\nThis is why we are getting everybody involved.\nThe more people who play this game, the more ideas your organization has on how to raise money and the more support it has when raising money and building the system that drives the strategy.\nWe believe people who plan together execute together.\nSo as you play, you're not simply answering questions.\nYou're learning how fundraising works, sharing your own wisdom and helping your organization build a strategy you can all understand and execute together.\nDon't worry about giving perfect answers.\nI'll walk you through it.\nLet's start.",
    "a1_intro": "Let's start with the most important question.\nWho should actually fund your mission?\nThis is important because not everybody is meant to fund your organization.\nOne of the mistakes organizations make is simply saying, we need donors, we need businesses or we need foundations.\nThat's too broad.\nThere are specific people who have a strong reason to care about the problem you solve.\nThere are specific businesses that have a reason to care about the people you serve, the community you work in or the outcome you're trying to create.\nAnd there are grantors whose funding priorities already align with your mission.\nSo your job is to find your people.\nBefore I guide you deeper, who do you think are the exact types of people, businesses and grantors with the strongest reason to fund your mission?\nJust share what comes to mind.",
    "a1_deeper": "Beautiful.\nNow let's go a little deeper.\nWhen I say identify your ideal funders, I don't mean simply saying parents, businesses or foundations.\nWe need to get specific enough that your organization can actually go out and find these people.\nFor individuals, think about who has experienced the problem you're solving.\nWho knows somebody affected by it?\nWho strongly believes in the change you're trying to create?\nWho benefits when the people or community you serve become stronger?\nWho is already spending their time, attention or money around issues connected to your mission?\nThen look at businesses.\nWhich businesses serve the same people you serve?\nWho employs them?\nWho sells to them?\nWho benefits when this community becomes stronger?\nWhich companies already support issues connected to your work?\nThen look at grantors.\nWho already funds your issue?\nWho funds the population you serve?\nWho funds your geography, your type of program or the outcome you're trying to create?\nThe clearer you are about who you're looking for, the easier the rest of fundraising becomes.\nSo based on that, who specifically should your organization be looking for?",
    "approval_review": "Great.\nI've taken what you shared and cleaned it up so that your organization can actually use it.\nTake a look at both versions.\nIf the fine-tuned version captures what you mean, use it.\nIf you prefer exactly what you said, keep your original.",
    "a2_intro": "Now that we know who we're looking for, the next question is where do we find them?\nBecause knowing your ideal funders is only useful if your organization can consistently put those people in front of you.\nThis is where fundraising begins to become a system.\nYou shouldn't wake up every morning wondering, who are we going to contact today?\nYou should already know where your ideal funders congregate and have a process that consistently helps your organization find them.\nSo looking at the people, businesses and grantors you identified, where do you think you can consistently find them?",
    "a2_deeper": "Now think about it this way.\nIf you're looking for Christians, you go to the church.\nIf you're looking for Muslims, you go to the mosque.\nWhy?\nBecause that's where they congregate.\nThe same thing applies to fundraising.\nThe exact people you're trying to reach are already somewhere.\nThey belong to communities.\nThey work somewhere.\nThey attend events.\nThey join professional associations.\nThey use particular platforms.\nThey belong to churches, clubs, alumni networks, Facebook groups, LinkedIn communities and professional networks.\nBusinesses also congregate.\nYou find them through chambers, trade associations, business networks, industry events, directories and LinkedIn.\nAnd grantors congregate too.\nYou find them through funding databases, community foundations, funder networks, existing grantee lists, conferences, information sessions and the people responsible for their funding programs.\nYou don't need to search everywhere.\nYou need to know where your people already are.\nBased on that, where should your organization consistently go to find the funders you identified?",
    "a3_intro": "Now let's talk about attraction.\nBecause knowing where your funders are does not mean you need to spend every day chasing them.\nThere are things your organization can put out there that will attract the right people to you.\nThere are things you can put out there that will attract the right businesses.\nAnd there are ways of positioning your organization that can attract the attention of grantors as well.\nSo before we talk about what those things could be, what do you think your organization can offer that would make your ideal funders want to stop, pay attention and connect with you?",
    "a3_deeper": "Now let's go a little deeper.\nThink about your ideal funders.\nWhat can you put in front of them that is already valuable to them?\nIt could be a guide.\nIt could be a report.\nA checklist.\nA survey.\nAn assessment.\nA webinar.\nAn event.\nA community activity.\nA campaign.\nA useful resource.\nAn opportunity to share their opinion.\nOr simply an invitation to become part of something they already care about.\nFor businesses, sometimes the attraction is simply starting the right conversation around something both your organization and that business care about.\nFor grantors, attraction can mean understanding their priorities, attending their information sessions, asking good questions and making sure they know your organization before an application ever lands in front of them.\nThis is very important.\nYour first interaction does not always have to be an ask.\nThe first goal is to get the right people to notice you, connect with you and give you the opportunity to build a relationship.\nBased on that, what can your organization offer your potential funders that gives them a reason to move toward you before you ask them for money?",
    "a4_intro": "Now we get to the actual fundraising process.\nFinding somebody is not fundraising.\nAttracting them is not fundraising either.\nYou still need a process that moves that relationship towards financial support.\nAnd this is where many organizations get it wrong.\nThey meet somebody for the first time and immediately ask them for money.\nThat's not a fundraising system.\nThere needs to be a clear process.\nSo before I walk you through ours, once potential funders connect with your organization, how do you think you should raise money from them?",
    "a4_deeper": "Now, this is one of the most important things I want you to learn from this game.\nYou don't raise money by meeting somebody for the first time and immediately asking them for money.\nPeople usually need to know you, like you and trust you before they are ready to give.\nSo the fundraising process we use is very simple.\nKnow.\nLike.\nTrust.\nAsk.\nFollow up.\nSteward.\nFirst is KNOW.\nThe potential funder needs to discover your organization and understand what you do.\nThen LIKE.\nGive them reasons to stay connected, pay attention and become interested in the work.\nThen TRUST.\nThey need to see your impact.\nThey need to trust your leadership.\nThey need to believe your organization can actually create the change you say you're creating.\nThen you ASK.\nAt that point, you clearly invite them to financially support the mission.\nAnd if they don't give immediately, you FOLLOW UP.\nDon't just disappear.\nContinue the relationship.\nFind out what they need.\nGive them more information.\nContinue the conversation.\nThen when they give, you STEWARD them.\nThank them.\nShow them what their support made possible.\nKeep them connected.\nBecause the goal is not simply to get one donation.\nThe goal is to build a relationship that can continue to support the mission.\nAnd remember, this process may look different for individuals, businesses and grantors.\nA grantor may need to know your organization long before your application comes in.\nA business may need several conversations before a partnership or sponsorship opportunity makes sense.\nAn individual may need to experience your stories, events, content and impact before making that first gift.\nBut the principle remains the same.\nKnow.\nLike.\nTrust.\nAsk.\nFollow up.\nSteward.\nNow based on this process, how should your organization move your potential funders from first connection to financial support and an ongoing relationship?",
    "lead_free_complete": "Beautiful.\nYou have now built the foundation of your organization's fundraising strategy.\nYou identified who should fund your mission.\nWhere to find them.\nHow to attract them.\nAnd the process your organization can use to raise money from them.\nBut remember something.\nIf you build this alone, you're most likely going to manage it alone.\nThe real power comes when your board builds it with you.\nBecause the more people who play the game, the more ideas you have on how to raise money and the more support you have when raising money and building the system that drives the strategy.\nSo now, let's bring your board into the game.",
    "reality_intro": "Great.\nNow we know your fundraising direction.\nBut we're not going to build a strategy that ignores where your organization is today.\nBefore we build the complete working strategy, we need to understand what you already have.\nDo you already have individual donors?\nDo you have businesses supporting you?\nDo you already have grantors?\nWho is presently helping with fundraising?\nWhat technology, materials, resources and tools are already available?\nBecause once we know what you already have, we can identify what needs to be strengthened, what needs to be added and what system needs to be built around the strategy you just created.\nSo let's look at your present reality.",
    "reality_donors": "Let's start with individuals.\nTell us what already exists.\nYou don't need a perfect donor database.\nWe simply need to understand the individual donor relationships your organization already has so we can build from there.",
    "reality_businesses": "Now businesses.\nThink beyond businesses that have already given you money.\nInclude businesses that sponsor you, provide resources, employ people connected to your mission or already have a relationship with the organization.\nWe want to know what we can build from.",
    "reality_grantors": "Now let's look at grantors.\nTell us who already funds you or has funded you before.\nExisting funding relationships are valuable because your future grant strategy should not ignore the relationships you have already built.",
    "reality_team": "Now let's look at people.\nEvery fundraising strategy needs people to execute it.\nThat could be you.\nStaff.\nVolunteers.\nBoard members.\nA contractor.\nOr people who help occasionally.\nTell us who is already involved so we know the capacity you currently have.",
    "reality_technology": "What fundraising technology and tools are you using right now? Tell us about the systems you actually use to find prospects, track relationships, communicate, receive donations, research funders or follow up. We want to build around what already exists before recommending anything new.",
    "reality_materials": "What fundraising materials and content do you already have? Think about your case for support, pitch deck, sponsorship materials, impact stories, donor emails, grant materials, videos, social content or anything else you use to explain the mission, attract attention or ask for support.",
    "reality_budget": "What are you already spending on fundraising, and what financial capacity is realistically available to execute the strategy? Include the costs you already know about. If there is no dedicated fundraising budget yet, say that clearly. We need the real starting point so the Board can build a practical budget.",
    "part_intro": "Now let's talk about you.\nA fundraising strategy cannot execute itself.\nSomebody has to help build the system.\nSomebody has to help run it.\nSomebody has to open doors.\nSomebody has to build relationships.\nSomebody has to ask.\nSomebody has to follow up.\nBut everybody does not have to do the same thing.\nAnd this is where organizations sometimes make a mistake.\nThey give every board member the same fundraising expectation, even when everybody has different strengths, relationships and experiences.\nWe don't want to do that.\nWe want you to tell us where you genuinely believe you can help.",
    "part_build": "First, let's look behind the scenes.\nRaising money is only one part of fundraising.\nSomebody also has to help build and manage the system that makes fundraising possible.\nThat could mean researching potential funders, recruiting people to help, maintaining the CRM, helping with technology, creating materials, organizing events, tracking follow-up or reviewing what's working and improving the strategy.\nLook through the options and choose the areas where you genuinely feel you can help.",
    "part_raise": "Now let's talk about actually raising money.\nAgain, everybody does not have to make the ask.\nMaybe your strength is making introductions.\nMaybe you can identify businesses.\nMaybe you know grantmakers.\nMaybe you're comfortable attending meetings.\nMaybe you're good at building relationships.\nMaybe you can make the ask.\nMaybe you would rather help follow up or steward people after they give.\nChoose the areas where you are genuinely willing to participate.",
    "part_time": "Now be realistic with this one.\nWe don't want to build a strategy around time you don't actually have.\nTell us what you can genuinely commit each month.\nIt is better to commit three hours and actually give three hours than commit ten and never have the time to do it.",
    "part_anything": "Before we finish, I want to give you one more opportunity to share anything we haven't asked.\nMaybe there's a person you know.\nA business.\nA grantor.\nAn opportunity.\nA fundraising idea.\nA concern.\nOr another way you believe you can help.\nIf something came to mind while playing the game, put it here.\nIf not, you can simply continue.",
    "board_complete": "Beautiful.\nYou're done.\nBut I want you to think about what you just did.\nYou didn't simply answer some fundraising questions.\nYou identified who should fund your organization's mission.\nYou thought about where those funders can consistently be found.\nYou identified ways to attract their attention.\nYou learned the process of moving potential funders through know, like, trust, ask, follow up and steward.\nAnd you told your organization exactly how you want to participate.\nYour ideas will now become part of the fundraising strategy your board builds together.\nAnd this is important.\nPeople who plan together execute together.\nBecause you were part of building the strategy, you now understand the thinking behind it and where you can help.\nWhen your board comes together, everyone's ideas will be brought into the same room so you can decide what the organization should prioritize.\nThank you for playing.\nYou're ready for Game Day or Game Night.",
    "lead_setup_complete": "Great.\nWe now have your fundraising direction, we understand what your organization already has and we know how you want to participate.\nThat's enough for us to begin building your working fundraising strategy.\nRemember, the strategy is the roadmap.\nIt tells you who you're raising money from, where to find them, how to attract them, the process to raise money from them and what your organization needs to execute.\nThe next step is bringing more people into the process.\nBecause the stronger the collective thinking behind the strategy, the stronger the strategy becomes.\nWe're taking you to your dashboard now.\nYour working strategy will be there as soon as it's ready, and you can continue preparing your board while we build it.",
}

# The first-question screens were retired. Each active teaching clip now opens with the
# context that used to live in that question, continues into the lesson, and ends with
# the single answer prompt shown on screen.
TEXTS.update({
    "a1_deeper": "Let's start with the most important question.\nWho should actually fund your mission?\nThis is important because not everybody is meant to fund your organization.\nOne of the mistakes organizations make is simply saying, we need donors, we need businesses or we need foundations.\nThat's too broad.\nThere are specific people who have a strong reason to care about the problem you solve.\nThere are specific businesses that have a reason to care about the people you serve, the community you work in or the outcome you're trying to create.\nAnd there are grantors whose funding priorities already align with your mission.\nSo your job is to find your people.\nNow let's go a little deeper.\nWhen I say identify your ideal funders, I don't mean simply saying parents, businesses or foundations.\nWe need to get specific enough that your organization can actually go out and find these people.\nFor individuals, think about who has experienced the problem you're solving.\nWho knows somebody affected by it?\nWho strongly believes in the change you're trying to create?\nWho benefits when the people or community you serve become stronger?\nWho is already spending their time, attention or money around issues connected to your mission?\nThen look at businesses.\nWhich businesses serve the same people you serve?\nWho employs them?\nWho sells to them?\nWho benefits when this community becomes stronger?\nWhich companies already support issues connected to your work?\nThen look at grantors.\nWho already funds your issue?\nWho funds the population you serve?\nWho funds your geography, your type of program or the outcome you're trying to create?\nThe clearer you are about who you're looking for, the easier the rest of fundraising becomes.\nSo based on that, who specifically should your organization be looking for?",
    "a2_deeper": "Now that we know who we're looking for, the next question is where do we find them?\nKnowing your ideal funders is only useful if your organization can consistently put those people in front of you.\nThis is where fundraising begins to become a system.\nYou shouldn't wake up every morning wondering who you are going to contact today.\nYou should already know where your ideal funders congregate and have a process that consistently helps your organization find them.\nThink about it this way.\nIf you're looking for Christians, you go to the church.\nIf you're looking for Muslims, you go to the mosque.\nWhy?\nBecause that's where they congregate.\nThe same thing applies to fundraising.\nThe exact people you're trying to reach are already somewhere.\nThey belong to communities.\nThey work somewhere.\nThey attend events.\nThey join professional associations.\nThey use particular platforms.\nThey belong to churches, clubs, alumni networks, Facebook groups, LinkedIn communities and professional networks.\nBusinesses also congregate.\nYou find them through chambers, trade associations, business networks, industry events, directories and LinkedIn.\nAnd grantors congregate too.\nYou find them through funding databases, community foundations, funder networks, existing grantee lists, conferences, information sessions and the people responsible for their funding programs.\nYou don't need to search everywhere.\nYou need to know where your people already are.\nBased on that, where should your organization consistently go to find the funders you identified?",
    "a3_deeper": "Now let's talk about attraction.\nKnowing where your funders are does not mean you need to spend every day chasing them.\nThere are things your organization can put out there that will attract the right people and businesses to you.\nThere are also ways of positioning your organization that can attract the attention of grantors.\nThink about your ideal funders.\nWhat can you put in front of them that is already valuable to them?\nIt could be a guide.\nIt could be a report.\nA checklist.\nA survey.\nAn assessment.\nA webinar.\nAn event.\nA community activity.\nA campaign.\nA useful resource.\nAn opportunity to share their opinion.\nOr simply an invitation to become part of something they already care about.\nFor businesses, sometimes the attraction is simply starting the right conversation around something both your organization and that business care about.\nFor grantors, attraction can mean understanding their priorities, attending their information sessions, asking good questions and making sure they know your organization before an application ever lands in front of them.\nThis is very important.\nYour first interaction does not always have to be an ask.\nThe first goal is to get the right people to notice you, connect with you and give you the opportunity to build a relationship.\nBased on that, what can your organization offer your potential funders that gives them a reason to move toward you before you ask them for money?",
    "a4_deeper": "Now let's make your fundraising idea practical.\nAt this stage, I don't want to give you our fundraising framework or replace your thinking with mine.\nI want to understand how you believe your organization should turn a connection with a potential funder into financial support.\nThink about what you would actually do after they connect with you.\nWould you start a conversation?\nInvite them somewhere?\nShow them something?\nBuild the relationship over time?\nPresent an opportunity?\nAsk for support?\nFollow up?\nKeep them involved afterwards?\nThere is no need to use special fundraising language.\nGive me your process in your own words, even if the ideas feel rough or out of order.\nWe will organize what you mean and make it practical without changing it into somebody else's strategy.\nSo, from first connection onward, what do you think your organization should actually do to raise money from them?",
    "approval_review": "Great.\nI've kept exactly what you wrote as your original idea and created an improved version that is clearer, more specific and easier for your organization to use.\nReview both versions.\nChoose your original idea, choose the improved version or go back and edit your answer.",
})

# Audience-based Individual Game. These scripts are generated from Admin when
# Rooney's live recording is ready; the customer only sees the audio controls.
TEXTS.update({
    "audience_opening": "Welcome. We are going to build practical fundraising ideas around your organization's goal. Start with the people who have the strongest reason to care, then think through why they would give, where to find them, what would attract them, what to ask them to fund and the process that can move them from first contact to support.",
    "audience_individuals_audience": "Start with individual donors. Think about the type or group of people with the strongest personal, community or values-based reason to help your organization reach this goal. Be specific enough that the organization could recognize and find them.",
    "audience_individuals_reason": "Now explain the reason. What connects these people to the mission, the people served or the outcome this fundraising goal will create?",
    "audience_individuals_where": "Think about where these people already gather, work, learn, worship, network or spend their attention. Name the places and channels where the organization can consistently find them.",
    "audience_individuals_attraction": "Before asking for money, give people a reason to engage. Think about useful information, an experience, an event, a story or another valuable opportunity that would earn their attention and contact details.",
    "audience_individuals_funding_ask": "Make the future ask concrete. What part of the goal should these individuals help fund, and what amount or giving range would make sense for each person?",
    "audience_individuals_process": "Now describe the relationship journey. Explain the practical steps from first discovery, to interest and trust, to the ask, follow-up and continued stewardship.",
    "audience_businesses_gate": "If you know a type of business with a strong reason to support this goal, continue. If no business audience comes to mind, it is all right to move forward without inventing one.",
    "audience_businesses_audience": "Which types of businesses have the strongest reason to sponsor the organization, its programs or the people it serves? Be specific about the business profile.",
    "audience_businesses_reason": "Explain why those businesses would care. Consider their customers, employees, location, values, community commitments or commercial connection to the people and outcome involved.",
    "audience_businesses_where": "Where can the organization find these businesses and the people who make sponsorship or community-investment decisions?",
    "audience_businesses_attraction": "What partnership value, credible evidence, useful opportunity or shared community outcome would earn a conversation with these businesses?",
    "audience_businesses_funding_ask": "What should these businesses sponsor or fund, and what contribution or sponsorship amount should the organization ask for?",
    "audience_businesses_process": "Describe the practical process from identifying the right business and decision maker, through introduction and relationship building, to the proposal, follow-up and partnership stewardship.",
    "audience_grantors_gate": "If you know a type of grantor that aligns with this mission or goal, continue. If none comes to mind, move forward without guessing.",
    "audience_grantors_audience": "Which type of foundation, public funder or other grantmaker has the strongest reason to fund this mission, program or outcome?",
    "audience_grantors_reason": "Explain why the organization's work aligns with that grantor type's priorities, population, geography or intended outcomes.",
    "audience_grantors_where": "Where can the organization identify these grantors, their priorities, application opportunities and the people responsible for the funding program?",
    "audience_grantors_attraction": "Grant fundraising begins before the application. Explain how the organization can demonstrate relevance, evidence, credibility and readiness to strengthen the relationship and the application case.",
    "audience_grantors_funding_ask": "What should the organization ask these grantors to fund, and what request amount or range fits the goal and intended work?",
    "audience_grantors_process": "Describe the full grant process, including research, qualification, relationship building, case development, application, follow-up, reporting and stewardship.",
    "audience_involvement": "Finally, think about where you would be comfortable and genuinely useful. Describe the introductions, research, outreach, relationship building, asking, follow-up or other fundraising support you would be willing to provide.",
})

for retired_id in ("a1_intro", "a2_intro", "a3_intro", "a4_intro"):
    TEXTS.pop(retired_id, None)

# Free Board Recruitment assessment. These clips lead the experience while the
# longer on-screen guidance remains optional behind “Read the guidance”.
TEXTS.update({
    "recruitment-free-entry": "Welcome. In the next few minutes, I am going to help you identify the exact types of board members your organization should recruit. Tell us about your mission, the board you have today, the areas your organization needs to do well and where you need stronger board support. You do not need formal language or perfect answers. Use your own words. We will compare what your organization needs with what your present board already brings, then show you the people you should look for. Complete the short form on this page to begin.",
    "recruitment-free-question-1-mission": "Let's begin with your mission. What does your organization exist to achieve, who do you serve and what change are you trying to create? Tell us in your own words. You do not need to make it sound formal. This gives us the context we need to recommend board members who fit your real mission.",
    "recruitment-free-question-2-current-board": "Now tell us about the board you have today. How many board members do you currently have, and how does each person presently help your organization? You can describe their roles, skills, experience or the areas they normally support. For example, you might have an accountant who helps with finance, an educator who advises on programs or someone with strong community relationships. If you do not currently have board members, simply tell us that.",
    "recruitment-free-question-3-important-areas": "Now think about what your organization needs to do really well in order to grow, raise money and achieve its mission. List the areas that genuinely matter to your success. These might include fundraising, marketing, sales, partnerships, community engagement, programs, finance, operations, technology, legal knowledge, government relations, volunteer management, corporate relationships, grant development, communications or lived experience. Add whatever is important to your organization.",
    "recruitment-free-question-4-support-needed": "Finally, where do you specifically need new board members to support your organization right now, and why? Think about the important areas you just identified. Which ones need stronger board-level support? Where are you currently struggling? What experience, relationships or leadership are you hoping new board members will bring? Be as specific as you can, because this answer helps us prioritize the right recruitment profiles for your organization.",
    "recruitment-free-result": "Your board recruitment result is ready. We compared the capabilities your organization needs with the support your present board already provides. On this page, you will see the areas your board already covers, the most important gaps and the exact board-member profiles we recommend you recruit. Review each profile carefully. It explains the experience to look for and why that person matters to your organization. When you are ready, continue to see the complete self-guided process for finding, selecting and onboarding these board members.",
    "recruitment-free-video-page": "You now know who your organization needs to recruit. The Self-Guided Board Recruitment System helps you carry out the rest of the process yourself. It takes you from these priority profiles to a professional recruitment campaign, applicant review, interviews, references, selection and onboarding. You will have the process, tools and materials you need at each step, and you can request help when you need it. Review the information on this page and choose the button when you are ready to start your board recruitment.",
    "rct_question_1": "Start with your mission statement. Your mission tells us who you serve, what change you are trying to create and the kind of experience, credibility and relationships your board may need. Use your real mission statement or explain it plainly in your own words.",
    "rct_question_2": "Now describe the board you already have and how each person helps the organization. We need to understand the capability already around the table so we do not recommend people simply because a skill sounds useful. Tell us what each current board member actually brings.",
    "rct_question_3": "Tell us the board members you believe you need. Founders usually already have instincts about the people they want around the table. Put those ideas here. We will preserve your thinking and evaluate it together with the rest of the information you provide.",
    "rct_question_4": "Tell us where the organization needs stronger board support and why. Think about the areas where progress is difficult, where leadership is thin, where relationships are missing or where professional expertise would strengthen the organization.",
    "rct_question_5": "What kind of board are you trying to build? Choose the model that best describes the board you want. This helps us recommend people who fit how you actually want the board to function, rather than building a board around generic titles.",
    "rct_question_6": "Why should somebody join your board? Think about the value of serving with your organization. What could a strong board member help build, learn, influence or become part of? Your answer will later help shape the way the opportunity is presented to potential board members.",
    "rct_how_this_works": "This dashboard takes you through your board recruitment one step at a time. Start by confirming the board members your organization needs. Then create and launch your recruitment campaign, review applicants, conduct interviews and references, select the right people and onboard them. Choose any tutorial topic to hear guidance for that part of the process.",
    "rct_identify": "Begin by identifying the exact board members your organization needs. Review the recommended profiles and compare them with what your present board already brings. Edit anything that needs to change, then approve the result. The approved profiles become the foundation for the recruitment materials you create next.",
    "rct_strategy": "Use your approved board-member profiles to build the recruitment strategy and application process. The system uses what you have already provided, so review the material carefully, add any missing organization details and approve it when it accurately reflects who you want to recruit.",
    "rct_launch": "When your strategy and application are ready, create the campaign materials for the channels you want to use. Review every item before publishing or sending it. Your board application link is included where applicants need it, and completed applications will appear in this dashboard.",
    "rct_review": "Review each applicant against the board role and experience your organization needs. You can also add people you discover through referrals, LinkedIn, networking or your existing relationships. When you want to interview someone, generate the interview guide for that applicant, conduct the conversation and record your decision.",
    "rct_references": "For applicants you decide to move forward, use this section to complete references, any appropriate background checks and the conditional appointment process. You control every communication and final decision. Once you select someone, send the agreements and Board Member Profile Form needed before onboarding.",
    "rct_onboarding": "Prepare for onboarding only after the selection and required documents are complete. Generate the facilitation guide, lead the onboarding conversation and confirm the new member's role, responsibilities, contribution and first steps. Their completed information can then be used to create their Board Member Portfolio.",
})

for retired_recruitment_id in (
    "recruitment-free-entry",
    "recruitment-free-question-1-mission",
    "recruitment-free-question-2-current-board",
    "recruitment-free-question-3-important-areas",
    "recruitment-free-question-4-support-needed",
    "recruitment-free-result",
):
    TEXTS.pop(retired_recruitment_id, None)


# Dashboard section guidance. These clips explain one stage of each paid pathway.
# They are editable in Admin and generated explicitly with ElevenLabs. No customer
# deployment is required after a script is edited and a new live clip is generated.
TEXTS.update({
    # Board Recruitment dashboard
    "dash_rct_questions": "Start here. Before we recruit anybody, we need to understand the board you have, the board you want and what your organization actually needs. You will answer six focused questions, one screen at a time. Use your own words. Do not try to sound formal. Your mission, present Board, the people you believe you need, the areas where you need stronger support, the kind of Board you want to build and why somebody should join all become the evidence we use to recommend the exact Board Members your organization should recruit. When you finish, return to the dashboard and the platform will begin identifying those profiles automatically.",
    "dash_rct_identify": "This section turns your six answers into the exact Board Member profiles your organization should recruit. Review each recommendation against the Board you already have and the work your mission requires. The goal is not to collect impressive titles. It is to identify people whose experience, relationships and capability fill a real gap. Edit anything that does not reflect your organization. Add a profile if your own judgment says someone important is missing. Once you approve the final list, those approved profiles become the foundation for your application, recruitment materials and candidate review.",
    "dash_rct_materials": "Now turn the approved Board Member profiles into a professional recruitment process. Review the Board application and the campaign materials the platform prepares from the information you have already approved. Make sure the opportunity explains the mission, the commitment, the role, the value of serving and the kind of people you are looking for. Edit anything that needs your voice or a missing fact. Do not approve material simply because it sounds polished. Approve it when it accurately represents the organization and the Board Members you genuinely want to recruit.",
    "dash_rct_launch": "This is where preparation becomes an active recruitment campaign. Review the final opportunity, the application link and the materials you will use to reach potential Board Members. Launch only when the application and recruitment message are accurate. Once the opportunity is live, applicants can come through the public form and people in the Board Applicant Network can be notified where appropriate. You can still recruit through referrals, LinkedIn, professional networks and your own relationships. The platform is here to organize the process, not limit where good candidates can come from.",
    "dash_rct_applicants": "Every applicant who completes your public form appears here automatically. You can also add people you find through referrals, networking or direct outreach. Open each person to review their application and résumé where available. Compare the person with the Board role you actually approved, not with a generic idea of a good Board Member. If you want to move someone forward, generate the interview invitation. If they are not the right fit, prepare the rejection email. Your decision here controls who moves into the interview stage.",
    "dash_rct_interviews": "Use this section for the people you have chosen to interview. Generate a tailored interview guide for each candidate. The guide uses the Board role you are recruiting for, your organization's needs, the candidate's application and résumé, and the information you provided earlier. Use it to have a real conversation, not simply to read questions at the candidate. When you are satisfied that somebody should move forward, completing this stage prepares them for reference checks and the next part of the selection process.",
    "dash_rct_references": "Reference checks help you verify what you learned during the application and interview stages. Use the existing automated reference process to request and collect references from the people connected to the candidate. Review what comes back before making the final appointment decision. The goal is not to create bureaucracy. It is to make sure the person you are bringing onto the Board is consistent with what they represented and with the responsibility you are about to give them.",
    "dash_rct_background": "Background checks should stay proportionate to your organization, your jurisdiction and the Board role. This section keeps the process simple. Use an appropriate local police, sheriff, disclosure service or reputable background-check provider where your organization needs one. Follow the laws and policies that apply to you. The platform does not decide who passes or fails a background check. You make that decision based on the role, your governance requirements and the information returned.",
    "dash_rct_onboarding_prep": "Before you appoint someone fully, prepare the onboarding session. Set the date and time, review the reusable onboarding material and make sure the new Board Member will understand the mission, the Board's role, how the organization works, what is expected from them and what the organization commits to provide. Once the onboarding details are ready, you can prepare the correct appointment communication. The purpose of this stage is to make sure appointment and onboarding feel like one connected transition into service.",
    "dash_rct_onboarding_session": "Run the onboarding session as a real conversation with the new Board Member. Use the shared presentation and the presenter notes to move through the organization, the Board's responsibilities, expectations, ways of working and the role this person is stepping into. Keep each screen focused and use your own organization information wherever possible. The goal is not simply to show slides. It is to make sure the new Board Member understands what they are joining and leaves knowing what happens next.",
    "dash_rct_portfolios": "The Board Member Portfolio turns the final appointment into a clear execution role. Review what the platform recommends for each person, then confirm or edit the role yourself. The Portfolio should reflect what the organization needs and what was actually agreed with that Board Member. Generate it only when the role is right. The finished Portfolio can be downloaded and shared with the Board Member, and it gives them a clear picture of how they will contribute instead of leaving them with a vague Board title.",

    # Board Fundraising Game dashboard
    "dash_bfg_founder_game": "Start by playing the Board Fundraising Game yourself. For individuals, and for any business or grantor audiences you know, identify who has the strongest reason to support the goal, why they would give, where to find them, how to attract them, what to ask them to fund and how much to ask, and the step-by-step process from first contact to support. Then document the present donors, businesses and grantors the organization already has and explain how you would feel comfortable helping. Your original ideas become your contribution before the Board adds its own thinking.",
    "dash_bfg_meeting": "Set the Board meeting where the organization will make the final fundraising decisions, and tell us when the money is actually needed. The funding deadline matters because the execution plan must be built backwards from reality. A thirty-day deadline should not produce the same plan as a one-hundred-and-twenty-day deadline. Save the meeting date, time, timezone and funding deadline here. These details also give the people you invite a clear reason to complete their individual Game before the Board meets.",
    "dash_bfg_board": "Now bring the Board into the process. Add each person's name and email and send their private Game invitation. They will answer the core fundraising questions and tell the organization how they are willing to participate in building the fundraising system and raising money. You can resend an invitation, copy the link and use the person-specific call script when somebody needs a direct follow-up. The purpose is not simply to collect answers. It is to make sure the people who will later be asked to execute have already contributed to the strategy.",
    "dash_bfg_group": "The Group Board Fundraising Game is where individual ideas become Board decisions. Keep the microphone running while the Board works through six decisions: funding audiences and why, where to find them, how to attract them and build credibility, what to ask them to fund and how much, the step-by-step fundraising process, and the specific role each person agrees to play. Discuss the options, check every idea the Board agrees with and add the exact agreed wording when the conversation improves an idea. The choices show what was agreed and the transcript captures the explanation and delegation.",
    "dash_bfg_strategy": "After the Group Game, the platform turns the Board's decisions and full transcript into a proper fundraising plan, not meeting minutes. It contains the goal and deadline, the individual, business and grantor audiences and why they will support, where to find them, how to attract them, what to ask them to fund and how much, the fundraising process and every Board Member's role. Review and edit the plan while it remains visible on participant screens. Every participant selects Adopt before you complete adoption and begin delegation.",
    "dash_bfg_execution": "This is where the Board moves from planning into execution. Review and confirm each person's delegation. Then send one email containing their strategy, Board Fundraising Portfolio and personal fundraising assistant, and ask them to bookmark it. About twenty-four hours later, send the separate Relationship Mapping email so each Board Member can recommend people, businesses and grantors in their network who match the audiences the Board agreed to pursue.",

    # Board Recommitment dashboard
    "dash_rec_questions": "Start by giving the Recommitment process the context it needs. Tell us your mission, why you need the Board to recommit now, what you need these Board Members to help the organization accomplish and the date by which you need that renewed commitment in place. Add your organization logo on the opening screen. These answers become the context for the Recommitment Forms, the response interpretation, the one-on-one conversations and the final Board Member Portfolios. Keep the answers honest and specific. You are not writing marketing copy. You are explaining why this Board needs to make a real decision about how it will serve.",
    "dash_rec_forms": "Prepare the Recommitment Form that fits the choice you want to offer. The Active Board and Advisory Board version does not offer stepping down. The Full Recommitment version gives the Board Member three paths: remain active and step up, move into an Advisory Board role or step down gracefully. Review the form introduction and the outreach email, edit them if needed and approve them when they sound like your organization. You can copy the form link and email, or add a Board Member by name and email and send the selected form directly from the platform.",
    "dash_rec_responses": "Every completed Recommitment Form appears here automatically. Open the response, download it if you want a record and use the interpretation to understand what the person is really telling you about their willingness, capacity and preferred path. Then generate the individual call script. The script should prepare you for the conversation that fits that person's response. Someone who wants to step up needs a different conversation from someone moving to Advisory service or stepping down. The form gives you a starting direction. The real agreement still happens in the conversation.",
    "dash_rec_decisions": "After the one-on-one conversation, record what you and the Board Member actually agreed. Then choose the final path: continue as an active Board Member, move into an Advisory role or step down. For active and Advisory Members, confirm or edit the exact role before generating a Portfolio. The Portfolio should reflect the agreement, not merely the person's form response. Active and Advisory Members can receive a Portfolio and execution support. Someone stepping down receives the appropriate departure communication instead. This final decision becomes the authoritative record of how the person will move forward.",

    # Strategic Planning dashboard
    "dash_sp_organization": "Start with what is true about the organization today. Tell us your mission, goals, objectives, every program, team structure, technology, marketing, partnerships, fundraising, budget and what you are presently doing versus what you believe needs to happen next. Add your organization logo on the opening screen. Do not try to write the final Strategic Plan here. This information is the starting reality the Board will test, challenge, protect and improve. Enter every program separately because each program deserves its own strategic discussion later.",
    "dash_sp_meeting": "Set the date, time and timezone for your next Board Strategic Planning Session. This gives the process a real meeting to prepare for and lets the invitation tell Board Members when their thinking will be brought together. Once the organization information and meeting are ready, the platform can prepare the Strategic Planning Form that both you and the Board will complete before the session.",
    "dash_sp_founder_form": "Complete the Strategic Planning Form yourself before inviting the rest of the Board. You are using the same form everybody else will use because your ideas should enter the process as your ideas, not as the automatic answer. Review the organization's mission, goals, objectives, programs and the rest of the strategy areas. Say what you believe should remain, improve or change. If the present mission is already right, you can explicitly choose to leave it the way it is. Your response will later sit alongside everybody else's thinking in the live session.",
    "dash_sp_board_forms": "Invite each Board Member to think before the meeting. Add their name and email and send the same Strategic Planning Form you completed. Every completed response appears here so you can view or download it, while incomplete responses can be reminded. Preserve the person's original thinking. The goal is not to force agreement before the meeting. It is to make sure everybody arrives having already thought seriously about the mission, goals, programs, people, resources and future direction of the organization.",
    "dash_sp_facilitation": "Generate the Strategic Planning Session Facilitation Guide after the responses are in. The guide prepares you to lead the Board through the areas that need real discussion, including differences in thinking, opportunities to clarify priorities and questions that will help the Board make decisions. It uses the organization information and the responses that were submitted. Download it and use it as your private facilitator support. It should help you get people talking and deciding, not replace the conversation with a script.",
    "dash_sp_session": "Run the Strategic Planning Session with one shared Board screen and private facilitator controls. The Board sees the ideas contributed for each strategic area while you guide the discussion and select what the Board agrees should shape the plan. Mission can stay exactly as it is when that is the decision. Every program is discussed separately. The microphone transcript captures the meaning behind the conversation, but your on-screen selections remain the authoritative Board decisions. When the final section is complete, the platform immediately begins preparing the Final Strategic Plan.",
    "dash_sp_plan": "Review the Strategic Plan produced from the organization's starting reality, the original participant contributions behind the selected ideas, the Board's live decisions and the meeting discussion. Edit anything that does not reflect what the Board agreed. You can give participants a review link before final adoption if they want time to read it. When you are satisfied, approve and adopt the plan. Then confirm what each person will actually carry forward. Do not assign responsibility simply because somebody suggested an idea. Confirm the role and responsibilities yourself before generating Leadership Portfolios and Executive Assistants.",
})

LABELS = {
    "lead_opening": "01 Lead User Opening",
    "board_opening": "02 Board Member Opening",
    "a1_deeper": "03 Area 1 Introduction + Teaching",
    "approval_review": "04 Original + Improved Idea Review",
    "a2_deeper": "05 Area 2 Introduction + Teaching",
    "a3_deeper": "06 Area 3 Introduction + Teaching",
    "a4_deeper": "07 Area 4 Introduction + Teaching",
    "lead_free_complete": "08 Lead Free-Game Completion",
    "reality_intro": "09 Current Reality Introduction",
    "reality_donors": "10 Current Individual Donors",
    "reality_businesses": "11 Current Businesses",
    "reality_grantors": "12 Current Grantors",
    "reality_team": "13 Current Fundraising Team",
    "reality_technology": "14 Current Fundraising Technology",
    "reality_materials": "15 Current Fundraising Materials And Content",
    "reality_budget": "16 Current Fundraising Budget",
    "part_intro": "17 Participation Introduction",
    "part_build": "18 Participation: Build & Manage System",
    "part_raise": "19 Participation: Raise Money",
    "part_time": "20 Participation: Time",
    "part_anything": "21 Participation: Anything Else",
    "board_complete": "22 Board Member Completion",
    "lead_setup_complete": "23 Lead User Post-Second-Form Completion",
    "recruitment-free-entry": "F01 Free Flow Entry",
    "recruitment-free-question-1-mission": "F02 Question 1 — Mission",
    "recruitment-free-question-2-current-board": "F03 Question 2 — Present Board",
    "recruitment-free-question-3-important-areas": "F04 Question 3 — Important Areas",
    "recruitment-free-question-4-support-needed": "F05 Question 4 — Support Needed",
    "recruitment-free-result": "F06 Result",
    "recruitment-free-video-page": "F07 Walkthrough Video Page",
    "rct_question_1": "RQ1 Mission",
    "rct_question_2": "RQ2 Present Board",
    "rct_question_3": "RQ3 Board Members Founder Thinks They Need",
    "rct_question_4": "RQ4 Areas Needing Support",
    "rct_question_5": "RQ5 Board Model",
    "rct_question_6": "RQ6 Why Someone Should Join",
    "rct_how_this_works": "R00 How This Works",
    "rct_identify": "R01 Identify The Board Members You Need",
    "rct_strategy": "R02 Build Your Recruitment Strategy",
    "rct_launch": "R03 Launch Your Recruitment Campaign",
    "rct_review": "R04 Review Applicants And Introductory Calls",
    "rct_references": "R05 References, Background Checks And Conditional Appointment",
    "rct_onboarding": "R06 Onboard Your New Board Members",
    "dash_rct_questions": "Recruitment 01 — Six Recruitment Questions",
    "dash_rct_identify": "Recruitment 02 — Identify Board Members Needed",
    "dash_rct_materials": "Recruitment 03 — Application And Recruitment Materials",
    "dash_rct_launch": "Recruitment 04 — Launch Recruitment Campaign",
    "dash_rct_applicants": "Recruitment 05 — Applicants",
    "dash_rct_interviews": "Recruitment 06 — Interviews",
    "dash_rct_references": "Recruitment 07 — Reference Checks",
    "dash_rct_background": "Recruitment 08 — Background Check",
    "dash_rct_onboarding_prep": "Recruitment 09 — Prepare Onboarding And Appointment",
    "dash_rct_onboarding_session": "Recruitment 10 — Run Onboarding Session",
    "dash_rct_portfolios": "Recruitment 11 — Board Member Portfolios",
    "dash_bfg_founder_game": "Fundraising 01 — Founder Board Fundraising Game",
    "dash_bfg_meeting": "Fundraising 02 — Board Meeting And Funding Deadline",
    "dash_bfg_board": "Fundraising 03 — Invite Board Members",
    "dash_bfg_group": "Fundraising 04 — Group Board Fundraising Game",
    "dash_bfg_strategy": "Fundraising 05 — Final Strategy And Delegation",
    "dash_bfg_execution": "Fundraising 06 — Share Strategy And Execute",
    "dash_rec_questions": "Recommitment 01 — Four Important Questions",
    "dash_rec_forms": "Recommitment 02 — Prepare And Send Forms",
    "dash_rec_responses": "Recommitment 03 — Responses And Conversation",
    "dash_rec_decisions": "Recommitment 04 — Final Outcomes And Portfolios",
    "dash_sp_organization": "Strategic Planning 01 — Organization Information",
    "dash_sp_meeting": "Strategic Planning 02 — Meeting",
    "dash_sp_founder_form": "Strategic Planning 03 — Founder Planning Form",
    "dash_sp_board_forms": "Strategic Planning 04 — Board Planning Forms",
    "dash_sp_facilitation": "Strategic Planning 05 — Facilitation Guide",
    "dash_sp_session": "Strategic Planning 06 — Live Session",
    "dash_sp_plan": "Strategic Planning 07 — Plan Adoption And Execution",
}

LABELS.update({key: key.replace("audience_", "Audience Game: ").replace("_", " ").title()
               for key in TEXTS if key.startswith("audience_")})

def narration_category(narration_id: str) -> str:
    if narration_id.startswith("recruitment-free-"):
        return "FREE_RECRUITMENT"
    if narration_id.startswith("rct_"):
        return "RECRUITMENT_DASHBOARD"
    if narration_id.startswith("dash_rct_"):
        return "DASHBOARD_AUDIO_RECRUITMENT"
    if narration_id.startswith("dash_bfg_"):
        return "DASHBOARD_AUDIO_FUNDRAISING_GAME"
    if narration_id.startswith("dash_rec_"):
        return "DASHBOARD_AUDIO_RECOMMITMENT"
    if narration_id.startswith("dash_sp_"):
        return "DASHBOARD_AUDIO_STRATEGIC_PLANNING"
    return "INDIVIDUAL_GAME"


STATIC_NARRATIONS = [
    {"narration_id": key, "game_step_id": key, "label": LABELS[key], "category": narration_category(key)}
    for key in TEXTS
]

PERSONALIZED_POINTS = []

DEFAULT_VOICE_SETTINGS = {
    "voice_enabled": True,
    "read_type_enabled": True,
    "default_mode": "voice",
    "narration_on": True,
    "personalization_on": False,
    "max_personal_clips": 0,
    "voice_provider": "elevenlabs",
    "voice_id": "",
    "browser_stt_on": False,
    "generic_fallback_on": True,
}
