"""Voice Guided Individual Game narration library.
ALL spoken text below is the owner's EXACT approved script — never rewritten, shortened or extended.
[FIRST NAME] is the only dynamic spoken variable (5 personalization moments)."""

TEXTS = {
    "c01": "We are going to do something very simple.\nWe are going to help you build the fundraising strategy your organization needs to reach its fundraising goal.\nTo raise money exponentially, you need to build your organization's fundraising system.\nTo build your organization's fundraising system, you need to know the exact type of people, businesses and grantors meant to fund your mission, where to find them, how to attract them and the exact process to raise money from them.\nThat's what we call the Fundraising Strategy.\nBy completing this game, you will create a clear fundraising strategy to reach your organization's fundraising goal.\nAnd don't worry about trying to give perfect answers.\nI am going to guide you through every step.\nWhen it is your turn, simply speak naturally.\nWe will turn what you say into text so you can see it, change anything you want and continue.\nReady?\nLet's get started.",
    "c02": "Great. Let's start with the most important question.\nNot every individual, business or grantor is meant to give to your mission.\nThere are people, businesses and grantors with strong reasons to give and see your mission succeed.\nBut many organizations simply say they are looking for donors, businesses or foundations.\nThat's too broad.\nWe want to identify the exact type of people, businesses and grantors meant to fund your mission or with the greatest reason to fund your organization.\nBefore I give you some questions to guide your thinking, I want to hear what comes to mind first.",
    "c03": "Who do you think are the exact types of people, businesses and grantors meant to fund your mission or with the greatest reason to fund your organization?\nDon't overthink it.\nJust share the ideas that come to mind.\nYour turn.",
    "c04": "Now let's think a little deeper.\nYou are not simply looking for people who have money.\nYou are looking for people with a reason to care.\nLet's start with individuals.",
    "c05": "Think about the individuals who have the greatest reason to want your mission to succeed.\nWho has personally experienced the problem your organization is solving?\nWho has a family member, friend or someone they care about affected by the problem?\nWho already strongly believes in the cause, issue or change your organization exists to create?\nWho benefits when the people or community you serve become stronger, healthier or more successful?\nWho already spends their time, attention or money supporting issues connected to your mission?\nWho has a personal, professional, community or emotional connection to the people you serve?\nAnd who has both a strong reason to care and the ability to financially support your mission?\nNow think about this carefully.\nDon't simply say parents.\nWhat kind of parents?\nParents of who?\nWhat has happened in their lives that gives them a reason to care?\nWhere do they live?\nWhat communities do they belong to?\nWhat makes them identifiable?\nYour answer should describe people you can actually go out and find.",
    "c06": "Now, based on what you just learned, who are the exact types of people with the greatest reason to fund your mission?\nBe as specific as you can.\nYour turn.",
    "c07": "Good.\nNow let's think about businesses.",
    "c08": "Which businesses serve the same people your organization serves?\nWhich businesses employ people from the communities or groups you serve?\nWhich businesses sell products or services connected to the problem your organization solves?\nWhich businesses benefit when the people or community you serve become stronger or more successful?\nWhich businesses have community investment, social impact or corporate responsibility priorities connected to your mission?\nWhich businesses are already supporting organizations, causes or communities similar to yours?\nAgain, don't simply say local businesses.\nWhat kind of businesses?\nWhat industry are they in?\nWhere are they located?\nWho do they serve?\nWhat gives them a strong reason to care about what your organization is doing?",
    "c09": "Now tell me.\nWhat are the exact types of businesses with the greatest reason to support your organization?\nYour turn.",
    "c10": "Excellent.\nNow let's think about grantors.",
    "c11": "Which grantors already fund the issue your organization is solving?\nWhich grantors fund the exact people or communities your organization serves?\nWhich grantors fund organizations working in your location?\nWhich grantors fund the type of program, intervention or outcome your organization creates?\nThe strongest grant opportunities usually come from funders whose existing funding focus already connects directly with your mission.\nSo don't simply say foundations.\nWhat type of foundation?\nWhat do they fund?\nWho do they fund?\nWhere do they fund?\nYou are looking for a profile you can actually search for and find.",
    "c12": "Now tell me.\nWhat are the exact types of grantors most likely to have a strong reason to fund your mission?\nYour turn.",
    "c13": "You are thinking strategically now.\nI am loving this.\nYou have identified the people, businesses and grantors we are going to build the rest of your fundraising strategy around.\nLet's keep going.",
    "c14": "Now that you know who you are looking for, finding them becomes much easier.\nAll you have to do is figure out where they congregate.\nIf you are looking for Christians, you go to the church.\nIf you are looking for Muslims, you go to the mosque.\nThe same principle applies to your funders.\nThe exact people, businesses and grantors you want already gather somewhere.\nThey belong to communities.\nThey attend events.\nThey join associations.\nThey use platforms.\nThey belong to professional networks.\nThey appear in directories.\nThey follow particular organizations.\nThey already congregate somewhere.\nYour job is to identify where.",
    "c15": "Looking at the people, businesses and grantors you identified, where do you think you can consistently find them?\nAgain, don't overthink it.\nGive me your first thoughts.\nYour turn.",
    "c16": "Great.\nNow let's make this practical.\nLook at the people you identified on your screen.\nWhere do these people already spend their time?\nWhere do they build relationships?\nWhere do they learn?\nWhere do they work?\nWhat communities do they belong to?\nWhat professional associations, Facebook groups, LinkedIn communities, churches, networks, events, clubs, conferences or organizations bring them together?\nWhere can you consistently find hundreds or thousands of people who match the profile you identified?",
    "c17": "Now tell me where you can consistently find the people you identified.\nYour turn.",
    "c18": "Great.\nNow look at the businesses you identified.\nWhere do businesses like these congregate?\nWhat industry associations do they belong to?\nWhat chambers of commerce?\nWhat business networks?\nWhat LinkedIn communities?\nWhat conferences or trade events?\nWhat directories already list them?\nWhere can you consistently find businesses that match the profiles you identified?",
    "c19": "Now tell me where you can consistently find the businesses you identified.\nYour turn.",
    "c20": "Excellent.\nNow look at the grantors you identified.\nWhere can you identify grantors like these?\nWhere can you see the organizations they already fund?\nWhere can you learn about their funding priorities?\nWhat funding databases, foundation directories, community foundations, grant networks, conferences or information sessions bring them together?\nWho are the program officers or executives responsible for the areas you care about?\nRemember, you don't need to search everywhere.\nYou need to go where the exact funders you want already congregate.",
    "c21": "Now tell me where you can consistently find the grantors you identified.\nYour turn.",
    "c22": "Excellent.\nNow you know who you are looking for and where to go to find them.\nLet's move to the part where fundraising starts becoming much easier.",
    "c23": "You don't have to run around chasing prospects.\nYou can provide something valuable that attracts them to your organization first.\nThink about it.\nIf the exact person you want to reach is already interested in something connected to your mission, what can you create or offer that makes them stop, pay attention and connect with you?\nThe first goal is not always to ask them for money.\nThe first goal is to attract their attention, get them to connect with your organization and create the opportunity to build the relationship.",
    "c24": "What can your organization offer the people, businesses and grantors you identified that would make them want to stop, pay attention and connect with you?\nShare the ideas that come to mind.\nYour turn.",
    "c25": "Great.\nNow let me show you what I mean.\nLook at one of the audiences you identified on your screen.\nWhat could your organization create, offer or invite them into that would be valuable enough for them to stop, pay attention and connect with you?\nIt could be a useful guide.\nA checklist.\nA report.\nA survey.\nAn assessment.\nA form.\nA webinar.\nAn educational session.\nAn event.\nA community activity.\nA call for change.\nA campaign they can participate in.\nA petition.\nA useful resource.\nAn opportunity to share their opinion.\nAn invitation to contribute to something meaningful.\nOr something else they would genuinely find valuable.",
    "c26": "For individuals, think about something useful enough for them to give you their contact details, register, join, respond or start engaging with your organization.\nGive them a reason to take that first step toward you.",
    "c27": "For businesses, you don't always need to begin by asking them to sponsor something.\nYou can create a reason to open a conversation.\nMaybe you want their opinion.\nMaybe you are inviting them into a community discussion.\nMaybe you are sharing information relevant to their employees or customers.\nMaybe you are asking them to participate in something connected to the community.\nThe first objective is to open the door.",
    "c28": "For grantors, understand what they care about before asking them for money.\nStudy what they fund.\nAttend their information sessions.\nRead their funding priorities.\nAsk good questions.\nConnect with program officers and relevant executives.\nGive yourself a reason to get your foot into the door and understand what they are trying to achieve.\nThe better you understand the funder, the better you can determine where your mission genuinely connects with what they already care about.",
    "c29": "You are thinking strategically now.\nI am loving this.\nLook at each audience on your screen.\nWhat can you offer each one that is valuable enough to attract their attention and get them to connect with your organization?\nLet's build this one audience at a time.\nYour turn.",
    "c30": "Great.\nNow you know who you want.\nYou know where to find them.\nAnd you know how you can begin attracting them to your organization.\nNow let's talk about how you actually raise money from them.",
    "c31": "Now we get to the actual fundraising process.\nYou don't raise money by reaching out to people when they connect with you for the first time and immediately asking them for money.\nThat's what a beggar does.\nAnd that's why people hardly give to them.\nAnd when people do give, they usually give money they can do away with.\nTo raise money, you must patiently follow a clear process that gets people to know you, like you and trust you before getting them to give.\nThat process is:\nKNOW.\nLIKE.\nTRUST.\nASK.\nFOLLOW UP.\nSTEWARD.",
    "c32": "Before I walk you through the process, once the people, businesses and grantors you identified connect with your organization, how do you think you should raise money from them?\nShare whatever comes to mind.\nYour turn.",
    "c33": "Great.\nNow let's walk through the process.",
    "c34": "First, KNOW.\nThey need to know your organization exists.\nThey need to understand the problem you are solving, who you serve and why your work matters.\nThat first interaction gets you on their radar.",
    "c35": "Then LIKE.\nGive them reasons to stay connected.\nLet them see stories.\nUseful information.\nThe people you serve.\nYour thinking.\nYour work.\nYour events.\nYour community.\nThe more meaningful interactions they have with your organization, the more interested they can become in what you are doing.",
    "c36": "Then TRUST.\nPeople give when they believe you can do what you say you are going to do.\nShow them your work.\nShow them your impact.\nHelp them understand your leadership.\nLet them see the people behind the mission.\nAnswer their questions.\nGive them reasons to trust that supporting your organization is worthwhile.",
    "c37": "Then ASK.\nWhen the relationship is ready, make the ask.\nBe clear.\nTell them what you are raising money for.\nTell them what their support can make possible.\nAnd ask them to financially support the mission.",
    "c38": "Then FOLLOW UP.\nNot everybody will say yes the first time.\nSome people need more information.\nSome need time.\nSome need another conversation.\nSome simply forgot.\nFollow up.\nStay connected.\nContinue the conversation.",
    "c39": "Then STEWARD.\nWhen somebody gives, don't disappear until you need money again.\nThank them.\nKeep them connected.\nShow them what their support made possible.\nContinue the relationship.\nGive them a reason to feel good about supporting your mission and a reason to support you again.",
    "c40": "Now imagine one of the audiences you identified sees something valuable your organization created and connects with you.\nThey now KNOW you.\nYou continue sharing useful information, stories, opportunities and conversations that connect them more deeply to your mission.\nThey begin to LIKE what you are doing.\nYou show them your impact, your work and why your organization can be trusted to create the change you promised.\nThey begin to TRUST you.\nWhen the relationship is ready, you ASK them to support your mission.\nIf they are not ready immediately, you FOLLOW UP.\nAnd when they give, you STEWARD the relationship by thanking them, showing them their impact and keeping them connected.\nThat's how fundraising becomes a system.\nYou stop running around chasing random people and asking strangers for money.\nYou build relationships with the exact people who already have a reason to care about your mission and patiently move those relationships toward financial support.",
    "c41": "Now you understand the process.\nLet's build yours.\nBased on what you just learned, what ideas come to mind for how your organization can move the people, businesses and grantors you identified through KNOW, LIKE, TRUST, ASK, FOLLOW UP and STEWARD?\nYou don't need to give a perfect answer.\nTell me how you think your organization can make this process work.\nYour turn.",
    "c42": "You just built the foundation of your fundraising strategy.\nYou identified the exact type of people, businesses and grantors meant to fund your mission or with the greatest reason to fund your organization.\nYou identified where to consistently find potential funders.\nYou identified how to attract their attention.\nAnd you worked through the exact process to raise money exponentially for your organization.\nNow let's talk about you.",
    "c43": "A fundraising strategy becomes powerful when people actually help execute it.\nAnd everybody does not have to fundraise in the same way.\nSome people are better at building the system behind fundraising.\nSome are comfortable introducing people.\nSome are good at research.\nSome can build relationships.\nSome can make the ask.\nSome can follow up.\nSome can create materials.\nSome can organize.\nSome can open doors.\nThe important thing is that you choose how you genuinely want to help.",
    "c44": "First, how would you like to help build and manage your organization's fundraising system?\nLook at the options on your screen and choose everything you would genuinely be willing to help with.\nThere is no perfect answer.\nChoose what actually fits you.",
    "c45": "Tell me how else you would like to help build or manage the fundraising system.\nYour turn.",
    "c46": "Great.\nNow let's look at how you personally want to help raise money.\nLook at the options on your screen and choose everything you would genuinely be willing to do.",
    "c47": "Tell me how else you would like to help raise money.\nYour turn.",
    "c48": "Excellent.\nOne more practical question.\nWe want your role to fit into what you can realistically do.\nHow much time can you realistically commit each month?\nChoose the option that works for you.",
    "c49": "Perfect.\nBefore we finish, I want to give you one more opportunity to share anything that has come to mind while playing the game.\nMaybe there is an idea we didn't ask about.\nMaybe there is a person, business, grantor, relationship, opportunity or fundraising idea you think the organization should explore.\nMaybe there is another way you would like to help.\nIf something is on your mind, this is your opportunity to share it.\nIf you don't have anything else, you can simply skip this question.\nOtherwise, go ahead.\nYour turn.",
    "c50a": "You have completed your Board Fundraising Game.\nYou now know the exact type of people, businesses and grantors meant to fund your mission or with the greatest reason to fund your organization.\nYou know where to consistently find potential funders.\nYou know how to attract their attention.\nAnd you understand the exact process to raise money exponentially for your organization.\nYour fundraising strategy is ready.\nNow imagine bringing your entire board into this process.\nThe more the people that play the game, the more ideas you have on how to raise money and the more support you have when raising money and building the system that drives the strategy.\nNow let's show you what happens when you bring your board into the game.",
    "c50b": "You have completed your Board Fundraising Game.\nYou have contributed your own thinking about who should fund the mission, where those funders can be found, how to attract them and how the organization can raise money from them.\nYou have also chosen how you want to participate.\nYour ideas are now part of the fundraising strategy your board will review together.\nAnd remember this.\nThe more the people that play the game, the more ideas you have on how to raise money and the more support you have when raising money and building the system that drives the strategy.\nNow let's show you the fundraising strategy you created.",
    "c51": "Great. Now that your Board Fundraising Game is unlocked, let's sharpen the strategy you created before we build the complete fundraising system around it.",
    "c52": "Take a look at how we have organized and fine-tuned your ideas.\nYou can use this version, keep your original idea or edit it in your own words.",
    "c53": "Excellent.\nNow we have your fundraising direction.\nNext, tell us what your organization already has so we can build the complete fundraising system around your present reality.",
    "c54": "You have decided who you want to raise money from, where to find them, how to attract them and the process to raise money from them.\nNow tell us what your organization already has.\nThis helps us build the fundraising system around your present reality instead of giving you a plan that ignores where your organization is today.",
    "c55": "Tell me about the individual donors currently giving to your organization.\nWho are they, how do they usually give and what do you know about why they support your mission?\nYour turn.",
    "c56": "Now tell me about the businesses currently giving to or supporting your organization.\nWho are they and what kind of support do they provide?\nYour turn.",
    "c57": "Now tell me about the grantors currently funding your organization.\nWho are they, what do they fund and how did you first connect with them?\nYour turn.",
    "c58": "Who currently helps your organization raise money and what does each person currently do?\nYour turn.",
    "c59": "Finally, what tools, technology, fundraising materials and other resources are you currently using to raise money and manage relationships with funders?\nYour turn.",
    "c60": "Great.\nNow we understand the fundraising strategy you want to execute and what your organization already has.\nLet's bring those pieces together and build the complete fundraising strategy around your present reality.",
    "f_p1": "Welcome to the Board Fundraising Game.",
    "f_p2": "Great.",
    "f_p3": "Now let's figure out where you can consistently find the funders you identified.",
    "f_p4": "Excellent.",
    "f_p5": "You did it.",
}

LABELS = {
    "c01": "Game introduction", "c02": "Round 1 opening", "c03": "Question 1 (first thoughts)",
    "c04": "Think deeper", "c05": "Individuals teaching", "c06": "People response",
    "c07": "Businesses transition", "c08": "Businesses teaching", "c09": "Business response",
    "c10": "Grantors transition", "c11": "Grantors teaching", "c12": "Grantor response",
    "c13": "Round 1 completion", "c14": "Round 2 teaching", "c15": "Question 3 (first thoughts)",
    "c16": "People finding teaching", "c17": "People finding response", "c18": "Business finding teaching",
    "c19": "Business finding response", "c20": "Grantor finding teaching", "c21": "Grantor finding response",
    "c22": "Round 2 completion", "c23": "Round 3 introduction", "c24": "Question 5 (first thoughts)",
    "c25": "Attraction teaching", "c26": "Individual attraction", "c27": "Business attraction",
    "c28": "Grantor attraction", "c29": "Question 6 (sharpen)", "c30": "Round 3 completion",
    "c31": "Round 4 introduction", "c32": "Question 7 (first thoughts)", "c33": "Process transition",
    "c34": "KNOW", "c35": "LIKE", "c36": "TRUST", "c37": "ASK", "c38": "FOLLOW UP", "c39": "STEWARD",
    "c40": "Complete process example", "c41": "Question 8 (build your process)", "c42": "Strategy completion",
    "c43": "Participation introduction", "c44": "Participation: build/manage", "c45": "Build: Other",
    "c46": "Participation: raise money", "c47": "Raise: Other", "c48": "Time commitment",
    "c49": "Final open question", "c50a": "Primary user ending", "c50b": "Board member ending",
    "c51": "Post-payment intro", "c52": "Fine-tuning area review", "c53": "After all four areas",
    "c54": "Current reality introduction", "c55": "Reality: individual donors", "c56": "Reality: businesses",
    "c57": "Reality: grantors", "c58": "Reality: team", "c59": "Reality: resources", "c60": "After current reality",
    "f_p1": "Fallback: welcome", "f_p2": "Fallback: after Question 1", "f_p3": "Fallback: into Round 2",
    "f_p4": "Fallback: after Question 8", "f_p5": "Fallback: completion",
}

STATIC_NARRATIONS = [{"narration_id": nid, "game_step_id": nid, "label": LABELS[nid]} for nid in TEXTS]

PERSONALIZED_POINTS = [
    {"point_id": "p1_welcome", "game_step_id": "intro", "label": "Personalized welcome", "fallback_id": "f_p1",
     "template": "Welcome to the Board Fundraising Game, [FIRST NAME]."},
    {"point_id": "p2_after_q1", "game_step_id": "round_1_q1", "label": "After Question 1", "fallback_id": "f_p2",
     "template": "Great, [FIRST NAME]."},
    {"point_id": "p3_round_2", "game_step_id": "round_2", "label": "Into Round 2", "fallback_id": "f_p3",
     "template": "Now, [FIRST NAME], let's figure out where you can consistently find the funders you identified."},
    {"point_id": "p4_after_q8", "game_step_id": "round_4_complete", "label": "After Question 8", "fallback_id": "f_p4",
     "template": "Excellent, [FIRST NAME]."},
    {"point_id": "p5_completion", "game_step_id": "completion", "label": "Completion", "fallback_id": "f_p5",
     "template": "You did it, [FIRST NAME]."},
]

DEFAULT_VOICE_SETTINGS = {
    "voice_enabled": True,
    "read_type_enabled": True,
    "default_mode": "voice",
    "narration_on": True,
    "personalization_on": True,
    "max_personal_clips": 5,
    "voice_provider": "elevenlabs",
    "voice_id": "",
    "browser_stt_on": True,
    "generic_fallback_on": True,
}
