"""Read-only prompt audit generator. Writes /app/memory/PROMPT_AUDIT.md. Modifies nothing."""
import asyncio, inspect, json, os, re, sys
sys.path.insert(0, "/app/backend")
os.chdir("/app/backend")
from dotenv import load_dotenv
load_dotenv("/app/backend/.env")

import ai_service
import workspace_service

OUT = ["# RESOURCE GENERATION PROMPT AUDIT — Complete, Verbatim",
       "", "Generated read-only from the live codebase. Nothing was modified.", "",
       "## ARCHITECTURE (applies to ALL 60 generation types)",
       "",
       "Every AI resource is generated by ONE engine: `ai_service.generate_structured(generation_type, context, instructions)`.",
       "Model/provider: Anthropic Claude via emergentintegrations LlmChat — model = env `CLAUDE_MODEL` (default `claude-sonnet-4-6`), key = `ANTHROPIC_API_KEY` or `EMERGENT_LLM_KEY`.",
       "",
       "FINAL RUNTIME REQUEST = SYSTEM MESSAGE (global, verbatim below) + USER MESSAGE assembled EXACTLY as (ai_service.py lines 495-502):",
       "```",
       'GENERATION TYPE: {meta[title]}',
       "",
       "CONTEXT (the only information you may use):",
       "{context}   <- built per flow (see CONTEXT BUILDERS below)",
       "",
       "SPECIAL REQUIREMENTS: {meta[note]}        <- per-resource dedicated prompt (verbatim per type below)",
       "",
       "ADDITIONAL INSTRUCTIONS:\\n{instructions}  <- per-call (founder remarks / edit requests), when present",
       "",
       "Respond with one JSON object matching exactly this schema (descriptions explain each field):",
       "{meta[schema] as indented JSON}            <- per-resource output schema (verbatim per type below)",
       "```",
       "Classification for EVERY resource: **B/C hybrid** — one shared assembly template + a DEDICATED per-resource `note` (instructions) and DEDICATED per-resource `schema` (output contract), plus flow-specific context builders. No prompt is generated by another AI (no type E). One chained case: material design adjustments (`resource_design_adjustments`) runs on an existing document.",
       ""]

OUT += ["## GLOBAL SYSTEM MESSAGE (sent as system prompt on every generation) — ai_service.py:334",
        "```", ai_service.SYSTEM_MESSAGE, "```", "",
        "## GLOBAL CAMPAIGN STANDARD (appended into campaign-type notes) — ai_service.py:15",
        "```", ai_service.CAMPAIGN_STANDARD, "```", "",
        "## REVIEW WARNING (deterministically appended AFTER generation to agreement display text — NOT sent to the AI) — ai_service.py:13",
        "```", ai_service.REVIEW_WARNING, "```", ""]

OUT += ["## CONTEXT BUILDERS (source, verbatim)", ""]
for fn_name in ["profile_context_text", "build_org_context", "application_context_text"]:
    fn = getattr(workspace_service, fn_name, None)
    if fn:
        OUT += [f"### workspace_service.{fn_name}", "```python", inspect.getsource(fn), "```", ""]

OUT += ["## ALL 60 GENERATION TYPES — dedicated instructions (note) + output schema, VERBATIM", ""]
MODBUCKET = {}
for key, meta in ai_service.GENERATION_TYPES.items():
    MODBUCKET.setdefault(str(meta.get("module", "?")), []).append(key)
    OUT += [f"### `{key}` — {meta['title']}",
            f"- module/location: {meta.get('module')}  |  per_application (candidate/board-member specific): {meta.get('per_application')}",
            "- DEDICATED INSTRUCTIONS (`note`, inserted as SPECIAL REQUIREMENTS):",
            "```", str(meta.get("note", "(none)")), "```",
            "- OUTPUT SCHEMA (inserted verbatim as the required JSON contract):",
            "```json", json.dumps(meta.get("schema", {}), indent=1), "```", ""]

OUT += ["## TYPES BY MODULE", "```", json.dumps(MODBUCKET, indent=1), "```", ""]

# Runtime example — replicate the exact prompt for a real user WITHOUT calling the AI.
async def runtime_example():
    from motor.motor_asyncio import AsyncIOMotorClient
    client = AsyncIOMotorClient(os.environ["MONGO_URL"])
    db = client[os.environ["DB_NAME"]]
    member = None
    profile = await db.recruitment_profiles.find_one({}, {"_id": 0, "user_id": 1})
    if profile:
        member = await db.members.find_one({"user_id": profile["user_id"]}, {"_id": 0})
    if not member:
        return "(no member with a recruitment profile in this environment)"
    context = await workspace_service.build_org_context(db, member["user_id"], member)
    meta = ai_service.GENERATION_TYPES["board_member_agreement"]
    prompt = (
        f"GENERATION TYPE: {meta['title']}\n\n"
        f"CONTEXT (the only information you may use):\n{context}\n\n"
        + (f"SPECIAL REQUIREMENTS: {meta['note']}\n\n" if meta.get("note") else "")
        + "Respond with one JSON object matching exactly this schema (descriptions explain each field):\n"
        + json.dumps(meta["schema"], indent=1))
    return prompt

example = asyncio.get_event_loop().run_until_complete(runtime_example())
OUT += ["## VERIFIED FINAL RUNTIME PROMPT (real data, real assembly path, AI NOT called)",
        "Resource: Board Member Agreement, for a real member in this environment. This is byte-identical to what "
        "`generate_structured` would send as the user message (system message above is sent separately).",
        "```", example[:30000], "```", ""]

open("/app/memory/PROMPT_AUDIT.md", "w").write("\n".join(OUT))
print("written", len("\n".join(OUT)), "chars;", len(ai_service.GENERATION_TYPES), "types")
