import { funnelControlsText } from "../content/appContent";
export const FunnelError = ({ name, error }) => error ? <p className="field-error" data-testid={`funnel-${name}-error`}>{error}</p> : null;

export const FunnelText = ({ name, label, value, update, error, required = true, type = "text", placeholder }) => <label className="field" data-testid={`funnel-${name}-field`}><span>{label}{required && <b> *</b>}</span><input type={type} value={value} placeholder={placeholder} min={type === "number" ? "0" : undefined} onChange={(event) => update(name, event.target.value)} data-testid={`funnel-${name}-input`} /><FunnelError name={name} error={error} /></label>;

export const FunnelTextarea = ({ name, label, value, update, error, helper, required = true }) => <label className="field" data-testid={`funnel-${name}-field`}><span>{label}{required && <b> *</b>}</span>{helper && <em className="field-helper" data-testid={`funnel-${name}-helper`}>{helper}</em>}<textarea rows="4" value={value} onChange={(event) => update(name, event.target.value)} data-testid={`funnel-${name}-textarea`} /><FunnelError name={name} error={error} /></label>;

export const FunnelRadioCards = ({ name, label, value, update, error, options }) => <fieldset className="field choice-field radio-cards-field" data-testid={`funnel-${name}-field`}><legend>{label} <b>*</b></legend><div className="radio-cards">{options.map((option) => <label className={`radio-card ${value === option.value ? "selected" : ""}`} key={option.value}><input type="radio" name={name} checked={value === option.value} onChange={() => update(name, option.value)} data-testid={`funnel-${name}-option-${option.value}`} /><strong>{option.title}</strong>{option.description && <span>{option.description}</span>}</label>)}</div><FunnelError name={name} error={error} /></fieldset>;

export const FunnelSelect = ({ name, label, value, update, error, options }) => <label className="field" data-testid={`funnel-${name}-field`}><span>{label} <b>*</b></span><select value={value} onChange={(event) => update(name, event.target.value)} data-testid={`funnel-${name}-select`}><option value="">{funnelControlsText.t_selectOne}</option>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select><FunnelError name={name} error={error} /></label>;

export const FunnelChoices = ({ name, label, value, update, error, options, helper }) => { const toggle = (option) => update(name, value.includes(option) ? value.filter((item) => item !== option) : [...value, option]); return <fieldset className="field choice-field" data-testid={`funnel-${name}-field`}><legend>{label} <b>*</b></legend>{helper && <em className="field-helper" data-testid={`funnel-${name}-helper`}>{helper}</em>}<div className="choice-grid">{options.map((option, index) => <label className={`choice ${value.includes(option) ? "selected" : ""}`} key={option}><input type="checkbox" checked={value.includes(option)} onChange={() => toggle(option)} data-testid={`funnel-${name}-option-${index + 1}`} /><span>{option}</span></label>)}</div><FunnelError name={name} error={error} /></fieldset>; };