import { useCallback, useEffect, useRef, useState } from "react";
import axios from "axios";
import { CheckCircle2, ClipboardList, Download, FileText, Lock, Mail, Mic, Search, Users } from "lucide-react";
import { BfgShell } from "@/game/gameShared";
import "@/game/game.css";
import "./guided-products.css";
import "./strategic-planning-dashboard.css";

const API=`${process.env.REACT_APP_BACKEND_URL}/api`;
const Button=({children,onClick,disabled=false})=><button type="button" className="bfg-btn bfg-btn-primary bfg-btn-sm" disabled={disabled} onClick={onClick}>{disabled&&<Lock size={14}/>} {children}</button>;
const Step=({n,title,open,setOpen,locked=false,children})=><section className={`sp-dash-card ${locked?"sp-locked":""}`}><button type="button" className="sp-card-toggle" onClick={()=>!locked&&setOpen(!open)}><span className="sp-step">{n}</span><span><strong>{title}</strong><small>{locked?"Complete the earlier steps to unlock this section.":open?"Close section":"Open section"}</small></span>{locked?<Lock size={20}/>:<span>{open?"−":"+"}</span>}</button>{open&&!locked&&<div className="sp-card-body">{children}</div>}</section>;

export default function StrategicPlanningDashboard(){
 const sid=new URLSearchParams(window.location.search).get("session_id")||"";
 const [ctx,setCtx]=useState(null),[community,setCommunity]=useState(null),[session,setSession]=useState(null),[busy,setBusy]=useState(""),[msg,setMsg]=useState("");
 const [open,setOpen]=useState("1"),[invite,setInvite]=useState({name:"",email:""}),[sessionStep,setSessionStep]=useState(0),[decisions,setDecisions]=useState({}),[transcript,setTranscript]=useState(""),[listening,setListening]=useState(false),[sessionShare,setSessionShare]=useState("");
 const [meeting,setMeeting]=useState({meeting_date:"",start_time:"",timezone_name:"",meeting_format:"Virtual",meeting_link:"",meeting_location:""}),[presentationStep,setPresentationStep]=useState(0),[presentationTranscript,setPresentationTranscript]=useState(""),[presentationShare,setPresentationShare]=useState(""),[finalDraft,setFinalDraft]=useState(""),[support,setSupport]=useState({support_type:"",message:""}),[supportSent,setSupportSent]=useState("");
 const recognition=useRef(null),presentationRecognition=useRef(null);
 const load=useCallback(async()=>{try{const w=await axios.get(`${API}/guided/strategic-planning/workspace`,{params:{session_id:sid}});setCtx(w.data);setCommunity(w.data.community_research||null);setFinalDraft(w.data.project?.final_plan?.display_text||"");const s=await axios.get(`${API}/guided/strategic-planning/session`,{params:{session_id:sid}});setSession(s.data);setDecisions(Object.fromEntries((s.data.sections||[]).map(x=>[x.key,x.selected_participant_id]).filter(x=>x[1])));setTranscript(s.data.transcript||"");const pm=w.data.project?.presentation_meeting||{};setMeeting(v=>({...v,...pm}));setPresentationStep(pm.current_area_index||0);if(pm.share_token)setPresentationShare(`${window.location.origin}/strategic-presentation/${pm.share_token}`);setPresentationTranscript(pm.transcript||"")}catch(e){setMsg(e.response?.data?.detail||"We could not load your Strategic Planning workspace.")}},[sid]);
 useEffect(()=>{load()},[load]);
 const act=async(key,fn)=>{setBusy(key);setMsg("");try{await fn();await load()}catch(e){setMsg(e.response?.data?.detail||"That action could not be completed yet.")}setBusy("")};
 const p=ctx?.project||{},respondents=p.participants?.filter(x=>x.status==="COMPLETED")||[],areas=p.areas||[],submitted=areas.filter(x=>x.plan_submitted_at||x.submitted_plan).length;
 const delegations=respondents.map(person=>({...person,assigned:areas.filter(a=>a.owner_participant_id===person.participant_id)})).filter(x=>x.assigned.length);
 const formReady=p.form?.status==="Approved",leadDone=p.participants?.some(x=>x.role==="Lead User"&&x.status==="COMPLETED"),sessionDone=session?.status==="COMPLETED",foundationReady=Boolean(p.plan?.display_text),allPlansReady=areas.length>0&&submitted===areas.length,presentReady=Boolean(p.final_plan?.display_text),presentationSaved=Boolean(p.presentation_meeting?.meeting_date),presentationDone=p.presentation_meeting?.status==="COMPLETED",approved=p.final_plan?.status==="Approved";
 const formLink=formReady?`${window.location.origin}/strategic-planning-form/${p.generic_form_token}`:"",leadLink=p.lead_form_token?`${window.location.origin}/strategic-planning-form/${p.lead_form_token}`:"",researchLink=community?.token?`${window.location.origin}/community-need-research/${community.token}`:"";
 const copy=t=>navigator.clipboard?.writeText(t);
 const listen=(kind)=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setMsg("Live transcription is not supported in this browser. Paste the meeting transcript into the box instead.");return}const r=new SR();r.continuous=true;r.interimResults=true;r.onresult=e=>{let text="";for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)text+=e.results[i][0].transcript+" ";if(text)(kind==="presentation"?setPresentationTranscript:setTranscript)(v=>(v+" "+text).trim())};r.onend=()=>setListening(false);r.start();(kind==="presentation"?presentationRecognition:recognition).current=r;setListening(kind)};
 const stop=()=>{recognition.current?.stop();presentationRecognition.current?.stop();setListening(false)};
 const moveSession=async i=>{setSessionStep(i);await axios.post(`${API}/guided/strategic-planning/session/progress`,{session_id:sid,current_section_index:i})};
 const movePresentation=async i=>{setPresentationStep(i);await axios.post(`${API}/guided/strategic-planning/presentation-meeting/progress`,{session_id:sid,current_area_index:i})};
 const uploadLogo=file=>{if(!file)return;const reader=new FileReader();reader.onload=()=>act("logo",()=>axios.post(`${API}/guided/strategic-planning/branding`,{session_id:sid,logo_data_url:reader.result}));reader.readAsDataURL(file)};
 if(!ctx)return <BfgShell><main className="guided-page"><section className="guided-section"><h1>Strategic Planning</h1><p>{msg||"Preparing your workspace…"}</p></section></main></BfgShell>;
 const card=(n,title,unlocked,content)=><Step n={n} title={title} locked={!unlocked} open={open===String(n)} setOpen={v=>setOpen(v?String(n):"")}>{content}</Step>;
 return <BfgShell><main className="guided-page sp-dashboard"><section className="guided-section sp-dash-head"><p className="bfg-eyebrow">STRATEGIC PLANNING WITH YOUR BOARD</p><h1>{ctx.organization_name||"Your Strategic Planning Dashboard"}</h1><p className="guided-intro">Your information moves upward through one process. Each AI-built output uses the organization facts, participant responses, Board decisions and meeting transcripts available at that stage.</p></section><div className="sp-dash-stack">
 {card(1,"Tell Us About Your Organization",true,<><p>Your saved organization intake is the foundation for every form, question, plan and portfolio that follows.</p><div className="sp-contentbox"><strong>Organization information saved</strong><p>Mission: {p.mission||"Saved with your intake"}</p><label><strong>Organization logo</strong><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>uploadLogo(e.target.files?.[0])}/></label></div></>)}
 {card(2,"Launch Community Need Research",true,<><p>This optional public survey asks what need exists, who experiences it, which approaches may work, what is missing and how the community can help. It also creates five promotional posts. Its responses become additional planning context, never automatic Board decisions.</p>{!community?<Button onClick={()=>act("research",()=>axios.post(`${API}/guided/strategic-planning/community-research`,{session_id:sid}))}><Search size={15}/> CREATE SURVEY AND PROMOTION KIT</Button>:<><div className="sp-linkbox"><span>{researchLink}</span><button onClick={()=>copy(researchLink)}>COPY LINK</button></div><p>{community.response_count||0} public responses received.</p></>}</>)}
 {card(3,"Generate Your Strategic Planning Form",true,<><p>The form uses your organization intake. Each section asks Board Members to review what exists and share what they would do differently, including the areas they can lead or support.</p>{!formReady?<Button onClick={()=>act("form",()=>axios.post(`${API}/guided/strategic-planning/prepare-form`,{session_id:sid}))}><ClipboardList size={15}/> GENERATE STRATEGIC PLANNING FORM</Button>:<div className="sp-linkbox"><span>{formLink}</span><button onClick={()=>copy(formLink)}>COPY FORM LINK</button></div>}</>)}
 {card(4,"Send The Form To Your Board Members",formReady,<><div className="sp-contentbox"><input placeholder="Board Member Name" value={invite.name} onChange={e=>setInvite({...invite,name:e.target.value})}/><input type="email" placeholder="Board Member Email" value={invite.email} onChange={e=>setInvite({...invite,email:e.target.value})}/><Button disabled={!invite.name||!invite.email} onClick={()=>act("invite",async()=>{await axios.post(`${API}/guided/strategic-planning/invite`,{session_id:sid,...invite});setInvite({name:"",email:""})})}><Mail size={15}/> SEND STRATEGIC PLANNING FORM</Button></div></>)}
 {card(5,"Complete Your Own Strategic Planning Form",formReady,<><p>The organization leader contributes through the same review process as the Board.</p><a className="bfg-btn bfg-btn-primary bfg-btn-sm" href={leadLink}>COMPLETE MY FORM</a>{leadDone&&<p><CheckCircle2 size={16}/> Your form has been completed.</p>}</>)}
 {card(6,"See Everyone Who Has Completed The Form",formReady,<>{!respondents.length?<p className="sp-empty">No completed responses yet.</p>:<div className="sp-people">{respondents.map(x=><article key={x.participant_id}><Users/><div><strong>{x.name}</strong><span>{x.role}</span></div><a href={`/strategic-planning-response/${x.participant_id}`} target="_blank" rel="noreferrer">VIEW RESPONSE</a></article>)}</div>}</>)}
 {card(7,"Start The Strategic Planning Session",respondents.length>0,<><p>Everyone can use a no-login shared screen that follows the facilitator. The microphone transcript and Board selections become the authority for the first strategy and delegation.</p><div className="sp-actions"><Button onClick={()=>act("guide",()=>axios.post(`${API}/guided/strategic-planning/facilitation-guide`,{session_id:sid}))}><FileText size={15}/> GENERATE FACILITATION GUIDE</Button>{!sessionShare?<Button onClick={async()=>{const r=await axios.post(`${API}/guided/strategic-planning/session/share`,{session_id:sid});setSessionShare(`${window.location.origin}/strategic-session/${r.data.share_token}`)}}>CREATE SHARED SCREEN LINK</Button>:<button onClick={()=>copy(sessionShare)}>COPY SHARED SCREEN LINK</button>}</div>{session?.sections?.length>0&&session.status!=="COMPLETED"&&<div className="sp-contentbox"><h3>{session.sections[sessionStep]?.title}</h3>{session.sections[sessionStep]?.ideas?.map(i=><label className="choice" key={i.participant_id}><input type="radio" checked={decisions[session.sections[sessionStep].key]===i.participant_id} onChange={()=>setDecisions({...decisions,[session.sections[sessionStep].key]:i.participant_id})}/><span><strong>{i.participant_name}</strong><br/>{i.idea}</span></label>)}<h4>Nonprofit Board Builder Recommended Ideas</h4><ul>{session.sections[sessionStep]?.recommendations?.map((x,i)=><li key={i}>{x}</li>)}</ul>{session.sections[sessionStep]?.allow_keep_current_mission&&<button onClick={()=>setDecisions({...decisions,[session.sections[sessionStep].key]:"__keep_current__"})}>LEAVE MISSION STATEMENT AS IT IS</button>}<button onClick={()=>setDecisions({...decisions,[session.sections[sessionStep].key]:"__use_all_ideas__"})}>USE BOARD DISCUSSION AND ALL IDEAS</button><div className="sp-actions">{sessionStep>0&&<button onClick={()=>moveSession(sessionStep-1)}>BACK</button>}{sessionStep<session.sections.length-1&&<Button disabled={!decisions[session.sections[sessionStep].key]} onClick={()=>moveSession(sessionStep+1)}>AGREE AND NEXT</Button>}</div></div>}<div className="sp-contentbox"><Button onClick={listening?stop:()=>listen("planning")}><Mic size={15}/> {listening==="planning"?"STOP TRANSCRIPTION":"START MICROPHONE TRANSCRIPTION"}</Button><textarea rows={7} value={transcript} onChange={e=>setTranscript(e.target.value)} placeholder="Live transcript or pasted meeting transcript"/></div>{session?.status!=="COMPLETED"&&<Button disabled={!session?.sections?.length||Object.keys(decisions).length<session.sections.length} onClick={()=>act("complete-session",()=>axios.post(`${API}/guided/strategic-planning/session/complete`,{session_id:sid,decisions,transcript}))}>COMPLETE STRATEGIC PLANNING SESSION</Button>}</>)}
 {card(8,"Generate The Foundational Strategy Plan",sessionDone,<><p>AI now receives the organization intake, all responses, selected directions, recommended ideas and the meeting transcript to build the plan discussed by the Board.</p><Button onClick={()=>act("foundation",()=>axios.post(`${API}/guided/strategic-planning/session-plan`,{session_id:sid}))}>GENERATE FOUNDATIONAL STRATEGY PLAN</Button>{foundationReady&&<div className="sp-contentbox"><p style={{whiteSpace:"pre-wrap"}}>{p.plan.display_text}</p></div>}</>)}
 {card(9,"Start First Delegation",foundationReady,<><p>Each selected contributor receives their assigned sections, the agreed direction, all ideas and meeting context.</p><div className="sp-area-grid">{delegations.map(x=><article key={x.participant_id}><h3>{x.name}</h3><p>{x.assigned.map(a=>a.area).join(", ")}</p><Button onClick={()=>act(`d-${x.participant_id}`,()=>axios.post(`${API}/guided/strategic-planning/send-delegation`,{session_id:sid,participant_id:x.participant_id}))}>SEND DELEGATION</Button></article>)}</div></>)}
 {card(10,"Track Board Members Building Their Detailed Plans",areas.length>0,<><div className="sp-progress"><strong>{submitted} of {areas.length} strategic area plans completed</strong><div><span style={{width:`${areas.length?submitted/areas.length*100:0}%`}}/></div></div><p>Each person can edit, approve, submit and download the detailed plan they will present to the Board.</p></>)}
 {card(11,"Generate The Present Strategic Plan",allPlansReady,<><p>This combines every submitted detailed area into the plan the Board will review during the presentation and delegation meeting.</p><Button onClick={()=>act("present",()=>axios.post(`${API}/guided/strategic-planning/final-plan`,{session_id:sid}))}>GENERATE PRESENT STRATEGIC PLAN</Button>{presentReady&&<div className="sp-contentbox"><textarea rows={20} value={finalDraft} onChange={e=>setFinalDraft(e.target.value)}/><Button onClick={()=>act("save-present",()=>axios.put(`${API}/guided/strategic-planning/final-plan/draft`,{session_id:sid,display_text:finalDraft}))}>SAVE EDITS</Button></div>}</>)}
 {card(12,"Schedule And Prepare The Presentation Meeting",presentReady,<><p>Save the meeting details, send the present plan to everyone and use the fixed guide to facilitate presentations, modifications and leadership delegation.</p><div className="sp-contentbox"><input type="date" value={meeting.meeting_date||""} onChange={e=>setMeeting({...meeting,meeting_date:e.target.value})}/><input type="time" value={meeting.start_time||""} onChange={e=>setMeeting({...meeting,start_time:e.target.value})}/><input placeholder="Time zone" value={meeting.timezone_name||""} onChange={e=>setMeeting({...meeting,timezone_name:e.target.value})}/><input placeholder="Meeting link or location" value={meeting.meeting_link||meeting.meeting_location||""} onChange={e=>setMeeting({...meeting,meeting_link:e.target.value})}/><div className="sp-actions"><Button disabled={!meeting.meeting_date||!meeting.start_time||!meeting.timezone_name} onClick={()=>act("meeting",()=>axios.post(`${API}/guided/strategic-planning/presentation-meeting`,{session_id:sid,...meeting}))}>SAVE MEETING DETAILS</Button><Button onClick={()=>act("p-guide",()=>axios.post(`${API}/guided/strategic-planning/presentation-meeting/guide`,{session_id:sid}))}>GENERATE PRESENTATION GUIDE</Button>{presentationSaved&&<Button onClick={()=>act("send-present",()=>axios.post(`${API}/guided/strategic-planning/presentation-meeting/send`,{session_id:sid}))}><Mail size={15}/> SEND PLAN AND MEETING DETAILS</Button>}</div></div>{p.presentation_meeting?.guide&&<div className="sp-contentbox"><p style={{whiteSpace:"pre-wrap"}}>{p.presentation_meeting.guide}</p></div>}</>)}
 {card(13,"Start The Presentation And Delegation Meeting",presentationSaved,<><p>The shared no-login screen follows the facilitator section by section. The recorded transcript captures modifications, approvals and delegated responsibility.</p><div className="sp-linkbox"><span>{presentationShare}</span><button onClick={()=>copy(presentationShare)}>COPY SHARED SCREEN LINK</button></div>{areas[presentationStep]&&<div className="sp-contentbox"><h3>{areas[presentationStep].area}</h3><p><strong>Presenter:</strong> {areas[presentationStep].owner_name}</p><p style={{whiteSpace:"pre-wrap"}}>{areas[presentationStep].submitted_plan||areas[presentationStep].direction}</p><div className="sp-actions">{presentationStep>0&&<button onClick={()=>movePresentation(presentationStep-1)}>BACK</button>}{presentationStep<areas.length-1&&<Button onClick={()=>movePresentation(presentationStep+1)}>NEXT SECTION</Button>}</div></div>}<div className="sp-contentbox"><Button onClick={listening?stop:()=>listen("presentation")}><Mic size={15}/> {listening==="presentation"?"STOP TRANSCRIPTION":"START MICROPHONE TRANSCRIPTION"}</Button><textarea rows={8} value={presentationTranscript} onChange={e=>setPresentationTranscript(e.target.value)} placeholder="Live transcript or pasted presentation meeting transcript"/></div><Button disabled={!presentationTranscript.trim()} onClick={()=>act("complete-presentation",()=>axios.post(`${API}/guided/strategic-planning/presentation-meeting/complete`,{session_id:sid,transcript:presentationTranscript}))}>COMPLETE PRESENTATION MEETING</Button></>)}
 {card(14,"Review, Edit And Approve The Final Strategic Plan",presentationDone,<><p>AI uses the present plan and only the modifications and delegation decisions supported by the second meeting transcript. You remain the final authority.</p><textarea rows={24} value={finalDraft} disabled={approved} onChange={e=>setFinalDraft(e.target.value)}/><div className="sp-actions">{!approved&&<><Button onClick={()=>act("save-final",()=>axios.put(`${API}/guided/strategic-planning/final-plan/draft`,{session_id:sid,display_text:finalDraft}))}>SAVE EDITS</Button><Button onClick={()=>act("approve",async()=>{await axios.put(`${API}/guided/strategic-planning/final-plan/draft`,{session_id:sid,display_text:finalDraft});await axios.post(`${API}/guided/strategic-planning/final-plan/approve`,{session_id:sid})})}>APPROVE FINAL PLAN</Button></>}<a className="bfg-btn bfg-btn-primary bfg-btn-sm" href={`${API}/guided/strategic-planning/final-plan/pdf?session_id=${encodeURIComponent(sid)}`}><Download size={15}/> DOWNLOAD</a></div></>)}
 {card(15,"Send The Final Plan And Create Leadership Portfolios",approved,<><p>The approved plan goes to the Board. Each portfolio uses organization context, the person’s contributions, their strategic sections and the confirmed presentation meeting delegation. Their secure AI assistant is included in the portfolio email.</p><div className="sp-actions"><Button onClick={()=>act("send-final",()=>axios.post(`${API}/guided/strategic-planning/send-final-plan`,{session_id:sid}))}><Mail size={15}/> SEND FINAL STRATEGIC PLAN</Button><Button onClick={()=>act("portfolios",()=>axios.post(`${API}/guided/strategic-planning/portfolios`,{session_id:sid}))}><CheckCircle2 size={15}/> GENERATE AND SEND PORTFOLIOS</Button></div></>)}
 {msg&&<p className="bfg-error">{msg}</p>}<section className="sp-dash-card"><h2>Ask For Help</h2><p>Send your question from inside the platform. We will be in touch through email.</p>{supportSent?<p className="member-success">{supportSent}</p>:<div className="sp-contentbox"><select value={support.support_type} onChange={e=>setSupport({...support,support_type:e.target.value})}><option value="">Choose what you need help with</option><option>Strategic Planning process</option><option>Facilitating the Board session</option><option>Delegation and detailed plans</option><option>Using the platform</option></select><textarea rows={5} value={support.message} onChange={e=>setSupport({...support,message:e.target.value})} placeholder="Tell us what you need help with"/><Button disabled={!support.support_type||!support.message.trim()} onClick={()=>act("support",async()=>{const r=await axios.post(`${API}/guided/strategic-planning/support`,{session_id:sid,...support});setSupportSent(r.data.message)})}>SEND SUPPORT REQUEST</Button></div>}</section>
 </div></main></BfgShell>;
}
