import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowRight, BriefcaseBusiness, Check, HeartHandshake, Mail, Target, UserRound } from "lucide-react";
import { ApplicantForm } from "@/components/ApplicantForm";
import { ApplicantConfirmation } from "@/components/ApplicantConfirmation";

const logoUrl = "https://customer-assets-jt897jd0.emergentagent.net/job_board-assessment/artifacts/2qaqmobl_Minimalist%20nonprofit%20logo%20design.png";
const steps = [[UserRound, "Create Your Professional Profile", "Tell us about your career, skills, experience and the professional relationships you can bring to a nonprofit board."], [Target, "Tell Us Where You Want to Make an Impact", "Choose the causes, communities and types of nonprofit organizations you would like to support."], [HeartHandshake, "Tell Us How You Want to Serve", "Share the board roles, fundraising activities, time commitment and working arrangements that fit you."], [Mail, "Receive Matching Board Opportunities", "We will email you whenever a nonprofit board opportunity matches your preferences and professional strengths."]];
const professions = ["Fundraising", "Finance and accounting", "Law and governance", "Marketing and communications", "Corporate partnerships", "Human resources", "Technology", "Healthcare", "Education", "Community development", "Program development", "Strategic planning", "Operations", "Government and public affairs", "Volunteer leadership", "Lived experience connected to nonprofit missions"];

const PublicHeader = () => <nav className="site-nav join-nav" data-testid="join-page-navigation"><a className="brand" href="/" data-testid="join-logo-link"><img src={logoUrl} alt="Nonprofit Board Builder" /></a><div className="nav-links"><a href="/#how-it-works">How It Works</a><a href="/#tools-materials">Tools and Materials</a><a href="/#success-stories">Success Stories</a><a href="/#my-story">My Story</a><a href="/join-a-board" className="active">Join a Board</a></div><a className="button button-small" href="#applicant-form" data-testid="join-nav-form-button">Join the Network</a></nav>;
const PublicFooter = () => <footer className="footer" data-testid="join-page-footer"><a className="brand footer-brand" href="/"><img src={logoUrl} alt="Nonprofit Board Builder" /></a><p>Nonprofit Board Builder helps nonprofits reactivate, recruit and activate powerhouse fundraising boards.</p><div className="footer-links"><a href="/">About</a><a href="/#how-it-works">How It Works</a><a href="/privacy-policy">Privacy Policy</a><a href="/terms">Terms</a></div></footer>;

export default function JoinBoardPage() {
  const [result, setResult] = useState(null);
  const navigate = useNavigate();
  const scrollToForm = () => document.getElementById("applicant-form")?.scrollIntoView({ behavior: "smooth" });
  if (result) return <><PublicHeader /><ApplicantConfirmation result={result} onHome={() => navigate("/")} /><PublicFooter /></>;
  return <main className="join-page" data-testid="join-a-board-page"><PublicHeader /><section className="join-hero"><div><p className="eyebrow" data-testid="join-hero-eyebrow">The Nonprofit Board Applicant Network</p><h1 data-testid="join-hero-heading">Join a Nonprofit Board Where Your Skills, Experience and Network Can Make a Difference</h1><p data-testid="join-hero-text">Tell us about your professional background, the causes you care about and the type of board opportunity you are looking for.<br /><br />We will save your profile and email you when we have nonprofit board opportunities that match your experience, interests, location and availability.</p><button className="button" onClick={scrollToForm} data-testid="join-hero-form-button">Join the Board Applicant Network <ArrowRight size={18} /></button><p className="hero-note"><Check size={17} /> Currently open to professionals living in the United States and United Kingdom.</p></div><div className="join-hero-art" aria-hidden="true"><div className="network-orbit"><span><UserRound /></span><i /><i /><i /><i /><div><BriefcaseBusiness size={34} /><strong>Skills meet mission</strong><small>Board Applicant Network</small></div></div></div></section><section className="section join-steps" data-testid="join-how-it-works"><p className="eyebrow">A clear path to board service</p><h2>Find the Right Nonprofit Board Opportunity in Four Steps</h2><div className="join-step-grid">{steps.map(([Icon, title, text], index) => <article key={title} data-testid={`join-process-step-${index + 1}`}><span>0{index + 1}</span><Icon size={25} /><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className="who-should-join" data-testid="who-should-join-section"><div className="who-heading"><p className="eyebrow light">Bring what you know</p><h2>Nonprofits Need More Than Names on Their Boards</h2><p>They need people willing to bring their skills, experience, relationships and commitment into the organization.</p></div><div className="profession-grid">{professions.map((profession, index) => <div key={profession} data-testid={`professional-area-${index + 1}`}><Check size={15} />{profession}</div>)}</div><p className="who-final" data-testid="who-should-join-final">You do not need previous board experience. You need a genuine commitment to contribute, learn and accept responsibility.</p></section><ApplicantForm onComplete={setResult} /><PublicFooter /></main>;
}