import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowRight, BriefcaseBusiness, Check, HeartHandshake, Mail, Target, UserRound } from "lucide-react";
import { ApplicantForm } from "@/components/ApplicantForm";
import { ApplicantConfirmation } from "@/components/ApplicantConfirmation";
import { joinBoardText } from "../content/appContent";
import { joinBoardPageText } from "../content/siteContent";

const logoUrl = "https://customer-assets-jt897jd0.emergentagent.net/job_board-assessment/artifacts/2qaqmobl_Minimalist%20nonprofit%20logo%20design.png";
const steps = [[UserRound, "Create Your Professional Profile", "Tell us about your career, skills, experience and the professional relationships you can bring to a nonprofit board."], [Target, "Tell Us Where You Want to Make an Impact", "Choose the causes, communities and types of nonprofit organizations you would like to support."], [HeartHandshake, "Tell Us How You Want to Serve", "Share the board roles, fundraising activities, time commitment and working arrangements that fit you."], [Mail, "Receive Matching Board Opportunities", "Receive real-time email updates when nonprofits using our platform launch new board opportunities."]];
const professions = ["Fundraising", "Finance and accounting", "Law and governance", "Marketing and communications", "Corporate partnerships", "Human resources", "Technology", "Healthcare", "Education", "Community development", "Program development", "Strategic planning", "Operations", "Government and public affairs", "Volunteer leadership", "Lived experience connected to nonprofit missions"];

const PublicHeader = () => <nav className="site-nav join-nav" data-testid="join-page-navigation"><a className="brand" href="/" data-testid="join-logo-link"><img src={logoUrl} alt={joinBoardPageText.nonprofitBoardBuilder} /></a><a className="button button-small" href="#applicant-form" data-testid="join-nav-form-button">Join the Network</a></nav>;
const PublicFooter = () => <footer className="footer" data-testid="join-page-footer"><a className="brand footer-brand" href="/"><img src={logoUrl} alt={joinBoardPageText.nonprofitBoardBuilder2} /></a><p>Nonprofit Board Builder connects professionals who want to serve with active board opportunities from nonprofits using our recruitment platform.</p><div className="footer-links"><a href="/">Nonprofit Board Builder</a><a href="/privacy-policy">Privacy Policy</a><a href="/terms">Terms</a></div></footer>;

export default function JoinBoardPage() {
  const [result, setResult] = useState(null);
  const navigate = useNavigate();
  const scrollToForm = () => document.getElementById("applicant-form")?.scrollIntoView({ behavior: "smooth" });
  if (result) return <><PublicHeader /><ApplicantConfirmation result={result} onHome={() => navigate("/")} /><PublicFooter /></>;
  return <main className="join-page" data-testid="join-a-board-page"><PublicHeader /><section className="join-hero"><div><p className="eyebrow" data-testid="join-hero-eyebrow">{joinBoardPageText.theNonprofitBoardApplicantNetwork}</p><h1 data-testid="join-hero-heading">{joinBoardText.h_joinANonprofitBoardWhere}</h1><p data-testid="join-hero-text">{joinBoardPageText.tellUsAboutYourProfessional}<br /><br />{joinBoardPageText.weWillSaveYourProfile}</p><button className="button" onClick={scrollToForm} data-testid="join-hero-form-button">{joinBoardPageText.joinTheBoardApplicantNetwork}<ArrowRight size={18} /></button><p className="hero-note"><Check size={17} />{joinBoardPageText.currentlyOpenToProfessionalsLiving}</p></div><div className="join-hero-art" aria-hidden="true"><div className="network-orbit"><span><UserRound /></span><i /><i /><i /><i /><div><BriefcaseBusiness size={34} /><strong>Skills meet mission</strong><small>Board Applicant Network</small></div></div></div></section><section className="section join-steps" data-testid="join-how-it-works"><p className="eyebrow">{joinBoardPageText.aClearPathToBoard}</p><h2>{joinBoardText.h_findTheRightNonprofitBoard}</h2><div className="join-step-grid">{steps.map(([Icon, title, text], index) => <article key={title} data-testid={`join-process-step-${index + 1}`}><span>0{index + 1}</span><Icon size={25} /><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className="who-should-join" data-testid="who-should-join-section"><div className="who-heading"><p className="eyebrow light">{joinBoardPageText.bringWhatYouKnow}</p><h2>{joinBoardText.h_nonprofitsNeedMoreThanNames}</h2><p>{joinBoardPageText.theyNeedPeopleWillingTo}</p></div><div className="profession-grid">{professions.map((profession, index) => <div key={profession} data-testid={`professional-area-${index + 1}`}><Check size={15} />{profession}</div>)}</div><p className="who-final" data-testid="who-should-join-final">{joinBoardPageText.youDoNotNeedPreviousExperience}</p></section><ApplicantForm onComplete={setResult} /><PublicFooter /></main>;
}