import { useEffect, useState } from "react";
import { memberApi } from "./api";

const OPTIONS = [[1,"Rarely"],[2,"Sometimes"],[3,"Usually"],[4,"Consistently"]];
const DIMENSIONS = [
  ["co_leader","Co-Leaders",["I involve board members in important leadership decisions before a direction is finalized.","Board members carry defined leadership responsibility for important organizational priorities."]],
  ["co_facilitator","Co-Facilitators",["Board members help lead important conversations, meetings or stakeholder engagements.","I create opportunities for board members to facilitate work rather than only attend meetings."]],
  ["co_architect","Co-Architects",["Board members help design the strategies, systems and structures the organization needs.","The board helps shape how the organization will achieve its mission, rather than only approving my plans."]],
  ["co_mobilizer","Co-Mobilizers",["Board members actively mobilize relationships, expertise, funding and other resources for the organization.","Each board member understands the people and resources they are responsible for helping the organization reach."]],
  ["co_evaluator","Co-Evaluators",["Board members regularly examine results and help decide what must improve.","The board uses evidence and organizational realities to evaluate progress against agreed priorities."]],
  ["co_reporter","Co-Reporters",["Board members help communicate the organization's progress and impact to important audiences.","Board members can clearly explain the mission, current priorities, results and needs of the organization."]],
];
export default function FounderBoardAudit(){
 const[open,setOpen]=useState(false),[answers,setAnswers]=useState({}),[result,setResult]=useState(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{memberApi.get("/guided/founder-board-audit").then(r=>{setAnswers(r.data.audit?.answers||{});setResult(r.data.audit?.result||null)}).catch(()=>{})},[]);
 const submit=async()=>{setBusy(true);setError("");try{const r=await memberApi.post("/guided/founder-board-audit",{answers});setResult(r.data.result)}catch(e){setError(e.response?.data?.detail||"Complete every question before seeing your result.")}setBusy(false)};
 return <section className="member-card" style={{marginTop:18}} data-testid="founder-board-audit"><h2>Founder / Executive Director Board Partnership Audit</h2><p>See how fully you are using your board as co-leaders, co-facilitators, co-architects, co-mobilizers, co-evaluators and co-reporters.</p><button className="button" onClick={()=>setOpen(!open)}>{open?"CLOSE AUDIT":result?"REVIEW MY AUDIT":"START FOUNDERS / EXECUTIVE DIRECTORS AUDIT"}</button>{open&&<div style={{marginTop:22}}>{DIMENSIONS.map(([key,label,questions])=><fieldset key={key} className="field choice-field"><legend><strong>{label}</strong></legend>{questions.map((question,i)=><div key={question} style={{margin:"16px 0"}}><p>{question}</p><div className="choice-grid">{OPTIONS.map(([value,text])=><label className={`choice ${Number(answers[`${key}_${i+1}`])===value?"selected":""}`} key={value}><input type="radio" name={`${key}_${i+1}`} checked={Number(answers[`${key}_${i+1}`])===value} onChange={()=>setAnswers({...answers,[`${key}_${i+1}`]:value})}/>{text}</label>)}</div></div>)}</fieldset>)}{error&&<p className="submit-error">{error}</p>}<button className="button" disabled={busy} onClick={submit}>{busy?"CALCULATING…":"SEE YOUR RESULT"}</button>{result&&<div className="member-success" style={{marginTop:22}}><h3>{result.stage}</h3><p><strong>{result.score} of {result.maximum}</strong></p><p>{result.summary}</p><p>{result.priority}</p>{result.dimensions.map(row=><p key={row.key}><strong>{row.label}:</strong> {row.score}/{row.maximum} · {row.level}</p>)}</div>}</div>}</section>
}
